### ISSUE TITLE
[Bug]: Problem with trailing slash in actix routes when deployed into the platform

### ISSUE THREAD

**Issue by robertohuertasm** [shuttle-hq/shuttle#1028]
### What happened?

So, I'm defining some actix routes as `films/`:

```rust
pub fn service<R: FilmRepository>(cfg: &mut ServiceConfig) {
    cfg.service(
        web::scope("/films")
            // GET
            .route("/", web::get().to(get_all::<R>))
            .route("/{film_id}", web::get().to(get::<R>))
            // POST
            .route("/", web::post().to(post::<R>))
            // PUT
            .route("/", web::put().to(put::<R>))
            // DELETE
            .route("/{film_id}", web::delete().to(delete::<R>)),
    );
}
```
When running `cargo shuttle run`, if I make a request to ``/films/` it works. It doesn't if I do `/films`. That's the expected.

The problem is that when I deploy this app to the platform, this behavior is different and no matter if I do /`films/` or `/films` I'm getting a 404.

I suspect there must be a component in the platform normalizing the paths and removing this trailing slash.

For the time being I'm removing the final slashes but it would be nice for this behaviour to be consistent both locally and remotely.

### Version

v0.18.0

### Which operating system(s) are you seeing the problem on?

In deployment

### Which CPU architectures are you seeing the problem on?

In deployment

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
Ah, so this happens because we use [tower-sanitize-path](https://github.com/shuttle-hq/tower-sanitize-path/tree/main) in our gateway proxy (which proxies requests to the users service). Perhaps we should just allow trailing slashes, as there doesn't seem to be a clear consensus on whether or not they should be used, and it getting cleared will be surprising to users. cc @chesedo

**Comment by oddgrd** [comment]
Resolved in https://github.com/shuttle-hq/tower-sanitize-path/pull/6, we just need to publish a release with the fix and we should be able to include the fix in Monday's release.
