### ISSUE TITLE
feature: support tide web framework

### ISSUE THREAD

**Issue by omac777** [shuttle-hq/shuttle#103]
As it stands you seem to have one example to do with rocket.

How about another example to support tide web infrastructure.
This link is tide/tls/bootstrap/structsy example:
https://gist.github.com/omac777/dc8dbd9b4fe574e7e01ad6bf9a8ee9d7
I would love to see how you would integrate it within shuttle.rs

Thank you in advance.

**Comment by christoshadjiaslanis** [comment]
Hey @omac777  - thanks for the feedback. `shuttle` now supports `axum` as well - and I think there is certainly interest in adding support for `tide` and others. 

I've created a public [roadmap item](https://github.com/orgs/getsynth/projects/4/views/2). We'll use this issue to gauge interest in Tide.

For anyone who may be interested in implementing Tide support, I would suggest looking at the [service crate](https://github.com/getsynth/shuttle/blob/main/service/src/lib.rs) to get started. 

If that is accompanied by a working minimal example that we can test in CI that would be even better!
