### ISSUE TITLE
[Improvement]: Allow SecretStore keys to be enumerable

### ISSUE THREAD

**Issue by RevCBH** [shuttle-hq/shuttle#1033]
### Describe the improvement

I created an `impl Source` from the [`config`](https://crates.io/crates/config) crate to allow pulling config values from a `SecretStore`. The config crate merges values from various sources when constructed, prior to querying. Since  `SecretStore` only has `new()` and `get()` methods, I couldn't enumerate the keys in the store and need to provide a whitelist of possible secret keys.

Maybe that's a good thing!

But I'm not sure what attacks this is preventing, as a malicious actor that can load the secret store could also just use unsafe code (via, say `std::mem::transmute`) to directly access the underlying `BTreeMap`.

So, if it's not a security concern in an adversarial context, it's primary purpose is to prevent accidentally leaking secret values.    I propose making the keys enumerable (but not values or (k,v) pairs) as I don't see why the names themselves would be considered sensitive, even if accidentally leaked.

---

If that's not acceptable, I can work around it by adding a macro that reads `Secrets.toml` at compile time to build the whitelist automatically, but that feels very kludgy to me.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by RevCBH** [comment]
I'm also happy to provide a PR, it's trivial once we've cleared the security concerns.

**Comment by jonaro00** [comment]
In 0.19, I added `into_iter()` on SecretStore. Does that help your use case?

I don't think there is any strict security policy around it. It is in the user's hands to handle it reasonably.

**Comment by RevCBH** [comment]
Ahh, yes. Sorry, I didn't realize I was still a version back. Thanks!
