### ISSUE TITLE
[Improvement]: Explain why 413 Request Too Large happens

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1035]
### Describe the improvement

0.19 introduces a 50MB limit on the deploy request (a compressed TAR archive of your files).

#1012 helps with this due to not uploading .git, but a user's project might still be too large.

The current error message is:
```
Error: 413 Payload Too Large
message: an unexpected error occurred. Please create a ticket to report this
```

We can
1. Print a friendly message when 413 happens (why it happened)
2. Check the body size of the outgoing request and deny the user if it will be too large. (refactor to use the same constant on both ends) (https://github.com/shuttle-hq/shuttle/pull/1031#issuecomment-1600757951)

(2) might make (1) obsolete, but I imagine there could be some rare case that slips through anyways...

@iulianbarbu Do you think we need (1), or just (2)?

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by ShouvikGhosh2048** [comment]
I'd like to work on this issue.
