### ISSUE TITLE
shuttle services down

### ISSUE THREAD

**Issue by tensuji** [shuttle-hq/shuttle#1051]
hello when I try to deploy my app: it gives me a 503 Service Unavailable. please advised

**Comment by joshua-mo-143** [comment]
Hey there, thanks for opening the issue - apologies that a response has taken so long.

What version of `cargo-shuttle` are you using, what version of shuttle dependencies are you using and have you tried restarting your project before deploying? (`cargo shuttle project restart`)

**Comment by tensuji** [comment]
Hi 

I don’t need to restart. I just evoke > Cargo Shuttle Status 

I do this twice and the bot is back online. I have to do that every 2 hours or so to keep the bot running, unless I am using and taking to the bot. 

Q: I deploy with  —allow-dirty 

Does that makes a difference?  



[dependencies]
anyhow = "1.0.66"
shuttle-serenity = "0.19.0"
shuttle-runtime = "0.19.0"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
shuttle-secrets = "0.19.0"
tokio = "1.26.0"
tracing = "0.1.37"


Guenson Lotin
ScipherDragon, Inc. 
Founder/CEO
The King of Ingenuity and Charisma
Producer, writer, Director, Editor
Filmmaker, Poet, Houdini VFX Artist
http://ScipherDragon.com
Studio: 310.496.0027

**Comment by jonaro00** [comment]
Sounds like your project goes idle, read this: https://docs.shuttle.rs/introduction/idle-projects

**Comment by tensuji** [comment]
Thanks. Got it.

Another question

I did a bot with shuttle directory: Sia

It seems that directory is corrupted and I can deploy to it, or restart a project with it. 

And suggestions
 




Guenson Lotin
ScipherDragon, Inc. 
Founder/CEO
The King of Ingenuity and Charisma
Producer, writer, Director, Editor
Filmmaker, Poet, Houdini VFX Artist
http://ScipherDragon.com
Studio: 310.496.0027

**Comment by jonaro00** [comment]
Do you mean static folder? In that case, there is also a docs page about that with tips and tricks and its caveats.

**Comment by tensuji** [comment]
I appraised you taking the time help.

Where is the caveats docs


Guenson Lotin
ScipherDragon, Inc. 
Founder/CEO
The King of Ingenuity and Charisma
Producer, writer, Director, Editor
Filmmaker, Poet, Houdini VFX Artist
http://ScipherDragon.com
Studio: 310.496.0027

**Comment by jonaro00** [comment]
Here are the static folder docs. https://docs.shuttle.rs/resources/shuttle-static-folder

**Comment by tensuji** [comment]
Hey , thanks for sending that info. 

But the info did not make sense to me. I’ve read it a bunch of times. 



Basically I created an app with the name Sia.  

It deploy find and was up and running. 

Then I deploy it again to make update to it. 

It fails. 

I tried to restart it, stop and start it, it just keep failing. 


I sense: that the Sia directory on shuttle is somehow corrected.

So Basically I can’t create an app call Sia anymore. 

I was hopping there was a way to delete the metadata on the Shuttle server so that it’s like I never created the app in the first place. 

I can create more apps just not an app name Sia. 


Does that make sense?  




Guenson Lotin
ScipherDragon, Inc. 
Founder/CEO
The King of Ingenuity and Charisma
Producer, writer, Director, Editor
Filmmaker, Poet, Houdini VFX Artist
http://ScipherDragon.com
Studio: 310.496.0027

**Comment by jonaro00** [comment]
Hmm, alright.
Generally, restarting a project with `cargo shuttle project restart` should reset it to a working state, but it is possible that the persistent data that stays between deploys can be corrupted.
In that case, yes, the project would need to be deleted an re-created.
However, this is not currently possible on shuttle (yet).
So, in the mean time, using a different project name will make a temporary solution.

**Comment by tensuji** [comment]
HelloI need to connect OpenAi (ChatGPT and Dall-e)  to my Discord bot.I already ccteate the Bot using Rust and serenity and add slash commands. I just need to add the OpenAi API key and have the Bot response with OpenAi messages or create an image.How do I do that in Rust? Do you have an example. Guenson LotinScipherDragon, Inc. Founder/CEOThe King of Charisma and IngenuityProducer, Writer, Director, EditorFilmmaker, Poet, Houdini VFX Artist…http://ScipherDragon.comStudio: 310.496.0027On Jun 29, 2023, at 7:44 AM, jonaro00 ***@***.***> wrote:﻿
Do you mean static folder? In that case, there is also a docs page about that with tips and tricks and its caveats.

**Comment by jonaro00** [comment]
There is no official way of implementing it, but I happen to have made a bot with similar functionality as a personal project. You can check "wallace-minion" repo on my profile.

**Comment by tensuji** [comment]
﻿Hey brotherI looked at your Wallace minion — and I’m more confused than I was.I feel like your code is badly written: very hard to understand what it does. I already created the Discord Bot: it can takes slash comments and send messages. Now all I need are:1) get OpenAI key from SecretStore 2) connect to OpenAi and select an OpenAi Model3) Get Discord user text prompt from slash commands 4) Pass the user text prompt to OpenAi5) Get OpenAi Result6) Pass the OpenAi Result as the Bot message This seems it can be done it a few line of codes. I’m using Serenity and Shuttle.RsAny guide thanks? Guenson LotinScipherDragon, Inc. Founder/CEOThe King of Ingenuity and CharismaProducer, writer, Director, EditorFilmmaker, Poet, Houdini VFX Artisthttp://ScipherDragon.comStudio: 310.496.0027On Jul 19, 2023, at 2:58 AM, jonaro00 ***@***.***> wrote:﻿
There is no official way of implementing it, but I happen to have made a bot with similar functionality as a personal project. You can check "wallace-minion" repo on my profile.

**Comment by jonaro00** [comment]
Wallace is a personal project with code readability as a second thought, so yes, it is a bit messy.
Once you've found the relevant parts, it should be possible to knit together everything.
Here are some guidelines:

1) Can easily be done by following Shuttle docs. The difficult part is passing it on to the command handlers with TypeMap. Use Serenity docs/examples for that.
2) Construct an OpenAI Client like https://github.com/jonaro00/wallace-minion/blob/master/src/discord.rs#L145 either in the command handler or as shared state like I do.
3) Will be different from my code since I don't use slash command. Use Serenity docs/examples.
4) and 5) can be done like this https://github.com/jonaro00/wallace-minion/blob/master/src/commands/ai_voice.rs#L107-L134
6) Should be easy.

**Comment by tensuji** [comment]
Thanks brother.I’ll keep working on it and let you know. Guenson LotinScipherDragon, Inc. Founder/CEOThe King of Charisma and IngenuityProducer, Writer, Director, EditorFilmmaker, Poet, Houdini VFX Artist…http://ScipherDragon.comStudio: 310.496.0027On Jul 22, 2023, at 6:26 PM, jonaro00 ***@***.***> wrote:﻿
Wallace is a personal project with code readability as a second thought, so yes, it is a bit messy.
Once you've found the relevant parts, it should be possible to knit together everything.
Here are some guidelines:

Can easily be done by following Shuttle docs. The difficult part is passing it on to the command handlers with TypeMap. Use Serenity docs/examples for that.
Construct an OpenAI Client like https://github.com/jonaro00/wallace-minion/blob/master/src/discord.rs#L145 either in the command handler or as shared state like I do.
Will be different from my code since I don't use slash command. Use Serenity docs/examples.
and 5) can be done like this https://github.com/jonaro00/wallace-minion/blob/master/src/commands/ai_voice.rs#L107-L134
Should be easy.

**Comment by tensuji** [comment]
How can I store the OpenAi API key using Shuttle Secret Store

Bellow I’m calling the DISCORD_TOKEN from there Serects.toml

The OPENAI_API is also there in Secrets.toml 

I want to access the  OPENAI_API that is in Secrets.toml then use it another Function: send_message_to_gpt3

The problem is when I set the OPENAI_APIin the Function Serenity I can’t access it in any other functions. 


Can this Macro be use in any functions: if so how?

#[shuttle_secrets::Secrets] secret_store: SecretStore, 





#[shuttle_runtime::main]
async fn serenity(
    #[shuttle_secrets::Secrets] secret_store: SecretStore,
) -> shuttle_serenity::ShuttleSerenity {
    // Get the discord token set in `Secrets.toml`
    let token = if let Some(token) = secret_store.get("DISCORD_TOKEN") {
        token
    } else {
        return Err(anyhow!("'DISCORD_TOKEN' was not found").into());
    };


async fn send_message_to_gpt3(message: &str) -> Result<String, reqwest::Error> {
 let api_key =  “OPENAI_API";


Guenson Lotin
ScipherDragon, Inc. 
Founder/CEO
The King of Ingenuity and Charisma
Producer, writer, Director, Editor
Filmmaker, Poet, Houdini VFX Artist
http://ScipherDragon.com
Studio: 310.496.0027

**Comment by jonaro00** [comment]
It needs to be inserted into the serenity client's `data` field so that it can be accessed from the command handlers. You can check Wallace's code or Serenity's examples folder for how to do it.
