### ISSUE TITLE
[Improvement]: Warn user if cargo-shuttle and shuttle-runtime are not compatible

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1053]
### Describe the improvement

This issue covers "alpha" projects (not shuttle-next, which already has a version check).

1. Add an explicit version flag check to `runtime/src/alpha/mod.rs`, just like the one in `runtime/src/bin/shuttle-next.rs`.
2. In `cargo-shuttle/src/lib.rs` in `get_runtime_executable`, before the outer else-clause returns the executable path, run the executable with the version flag and check if it is semver compatible with cargo-shuttle. Code in the `check_version()` function can be re-used or refactored to achieve this.
3. If the versions are not compatible, print a visible warning that notifies the user of this difference and suggests what action is recommended (cargo install or upgrade dependencies), but keep running the program.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by AllMight2099** [comment]
Hi there!
Can I pick this up?

**Comment by jonaro00** [comment]
Sure!

**Comment by d4ckard** [comment]
Hey 👋,
I'd like to fix this issue so I started looking to your suggestions. Adding a `--version` flag to `runtime::alpha::start` requires only a bit of logic. However, I would prefer to add this flag to `runtime::alpha::args::Args` instead to not give it any special treatment. This would require implementing boolean flags for the `runtime::alpha::args::args` macro. Is there anything forbidding such an  addition?
The difference between a boolean flag and a normal flag is that the boolean flat doesn't expect any arguments. If there isn't  we would have to introduce a type-check to the loop that goes through all the arguments passed to the `parse` method. Since we have the type of the field at compile-time, `std::any::type_name<$ty>` could be used to check at runtime if this is a boolean flag.
Is there maybe a better way to only perform compile-time checks?

**Comment by jonaro00** [comment]
Hi @d4ckard.

The reason for using such a naive approach for parsing the args is that those args are passed internally between the shuttle crates, and errors should only occur if a developer messes up. `clap` was moved away from in order to keep the dependency tree lighter. I would not say there is much reward for expanding this arg parsing method to more generalized cases until there is a need for it (I tend to think *keep it simple and only abstract things when repetition is introduced*).

All in all, your suggestion wouldn't hurt, but IMO it is not strictly needed. Feel free to use it as a learning opportunity though! Sadly I don't have a good answer for the parsing related questions.

**Comment by d4ckard** [comment]
I tried implementing boolean flags for `args!`. Unfortunately this didn't work out  without introducing additional complexity. Checking if the type of the field is `bool` can be accomplished using traits as shown in [this comment](https://users.rust-lang.org/t/how-to-check-types-within-macro/33803/5). What I didn't consider was that when using the `--version` flag any arguments that are required by default must become optional. This can't be easily implemented without giving up the type-safety of the arguments that are parsed by wrapping everything in `Option`s. I decided to just check for `--version` upfront now instead.

**Comment by d4ckard** [comment]
Here are the warnings and hints I added to `cargo-shuttle/src/lib.rs` if the versions don't match. The style used for the hints is similar to that in `runtime/src/alpha/mod.rs`. Any suggestions on wording or otherwise improving the hints?
```
Warning: shuttle-runtime and cargo-shuttle are not the same version.
[HINT]: cargo-shuttle is on version 0.21.0. Check this project's Cargo.toml if shuttle-runtime matches this.
[HINT]: If cargo-shuttle was installed using cargo, you can get the latest version by running `cargo install cargo-shuttle`.
```

**Comment by jonaro00** [comment]
That looks nice, but it would be good if both versions are displayed, and that the hint tells you which one to upgrade, and how (cargo install / update the toml). Also make sure the warning prints only if the versions are *not compatible*.

Thinking about it, it would be nice if the versions of
- cargo-shuttle
- the API (think shuttle-gateway)
- (upcoming) builder
- shuttle-deployer
- shuttle-runtime of the user's project

were all checked and logged throughout a deployment. This is a bigger job though, so we can keep that for another PR.

**Comment by d4ckard** [comment]
What exactly qualifies two versions as being compatible? Currently `check_version` simply tests for equality between the two versions. This doesn't mean that it is impossible for two different versions to be compatible, if they don't differ in any what that is relevant here.

> it would be good if both versions are displayed, and that the hint tells you which one to upgrade, and how

I'll add those improvements to the pull request (I checked this issue before opening it, but I didn't reload the tab so I didn't see your comment).
