### ISSUE TITLE
[Improvement]:  cargo-shuttle init functionality based on cargo-generate gets confused by git configuration

### ISSUE THREAD

**Issue by iulianbarbu** [shuttle-hq/shuttle#1081]
### Describe the improvement

A Shuttle user tried to init a `poise` project but it resulted in an error coming from `cargo-generate`: https://cdn.discordapp.com/attachments/1127489400985620520/1127489401207935016/image.png.

We understood later that this was caused by some git configuration present on the user machine:
```
[url "git@github.com:"]
   insteadOf = https://github.com/
```

We want to understand if `cargo-shuttle` can check whether the git configuration present on users' machines can cause similar problems for `cargo-generate`. This might require looking into the `cargo-generate` codebase to understand how it accounts for the git configuration (possibly through a rust git lib) and see if we can provide any useful checks upstream that would either fix the issue or propagate useful errors to users of `cargo-generate` lib.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by jonaro00** [comment]
cargo-generate is no longer used
