### ISSUE TITLE
[Bug]: The install instructions do not work

### ISSUE THREAD

**Issue by RaphaelDarley** [shuttle-hq/shuttle#1083]
### What happened?

the README says to use the command cargo install binstall which does not make cargo binstall work as the cargo-binstall crate is required. Compiling cargo-binstall from source with cargo install cargo-binstall is currently broken for me because it uses deprecated features in once_cell, but it can be installed. This adds a significant barrier when installing cargo shuttle as the compile time is significant particularly on a vm.

### Version

0.21.0

### Which operating system(s) are you seeing the problem on?

Windows, Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
Thanks for catching the typo in the README. Will fix.
To save time when installing cargo-binstall, you can go and download their binary like this https://github.com/cargo-bins/cargo-binstall#installation
This makes it possible to install cargo-binstall and cargo-shuttle in seconds.

**Comment by RaphaelDarley** [comment]
thanks, I found that eventually. could you give a similar script to install the binary of shuttle directly like cargo-binstall does.
I gave up the first time trying to use shuttle because the compile time was so long.

**Comment by jonaro00** [comment]
When binstall is installed from source, you can run it to get cargo-shuttle quickly. If two commands are too much, you can curl or wget the latest release https://github.com/shuttle-hq/shuttle/releases with one command. The advantage with binstall is that you get the latest version without having to think.
