### ISSUE TITLE
[Improvement]:  Improve error logging messages in shuttle-codegen for user client

### ISSUE THREAD

**Issue by joshua-mo-143** [shuttle-hq/shuttle#1086]
### Describe the improvement

I'd like to look at improving error logging messages in `shuttle-codegen` - namely, expanding on the error logging when certain specific errors are encountered (namely errors like os error 2: Could not be found).

Should not be too much effort and will greatly improve DX as it'll prevent common issues being asked in the Discord as much.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by Shubham8287** [comment]
Hi, looking to stab into this.

**Comment by joshua-mo-143** [comment]
> Hi, looking to stab into this.

Hey there - feel free to do so if you haven't already! I'm looking to try and get some changes done on this maaaaybe this week if I get around to it.

**Comment by Shubham8287** [comment]
hi, you can take it up in that case, I am busy with other stuff lately.

**Comment by oddgrd** [comment]
Hey @joshua-mo-143, where is this error coming from in the codegen?
