### ISSUE TITLE
[Bug]: Website::Projects page doesn't load on Safari

### ISSUE THREAD

**Issue by vibdev** [shuttle-hq/shuttle#1089]
### What happened?

Project cards, project list, and avatar don't load on safari. 

<img width="741" alt="Screenshot 2023-07-15 at 9 29 46 AM" src="https://github.com/shuttle-hq/shuttle/assets/1562615/05ea5d43-8fdb-406a-83e3-16cce551061e">

### Version

v0.21.0

### Which operating system(s) are you seeing the problem on?

macOS

### Which CPU architectures are you seeing the problem on?

ARM64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
Some people in Discord also had issues with this earlier today.

To debug a bit:

Does `cargo shuttle project list` show your projects?

Also, are you using the same account in the console as you used to get the Shuttle API key?

**Comment by vibdev** [comment]
`cargo shuttle project list` shows the projects as expected

I am using the same account and it works fine in Chrome.

**Comment by oddgrd** [comment]
Hey @vibdev, are you still experiencing this? @GugaGongadze, have you seen this before?
