### ISSUE TITLE
[Bug]: A project with the same name already exists

### ISSUE THREAD

**Issue by sparkyvxcx** [shuttle-hq/shuttle#1097]
### What happened?

As I was following the shuttle newsletter from a freshly installed Ubuntu VM environment, I encountered an issue while trying to `cargo shuttle init` and `cargo shuttle project start`, as these two commands return a vague message that says "a project with the same name already exists":

<img width="522" alt="Screenshot 2023-07-20 at 7 36 20 AM" src="https://github.com/shuttle-hq/shuttle/assets/24603835/d8868c65-1b70-43a6-a00c-6ffeb05e809d">

Apparently, from the shuttle console web interface, I don't have any projects:
<img width="1039" alt="Screenshot 2023-07-20 at 8 01 53 AM" src="https://github.com/shuttle-hq/shuttle/assets/24603835/23426596-006a-45ba-a0f9-d33fcb4026e3">

### Version

0.21.0

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
See above
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
Project names must be unique. If one does already exist, use a different one. Here are ways to modify which project name Shuttle uses: https://docs.shuttle.rs/configuration/shuttle-service-name

**Comment by sparkyvxcx** [comment]
> Project names must be unique. If one does already exist, use a different one. Here are ways to modify which project name Shuttle uses: https://docs.shuttle.rs/configuration/shuttle-service-name

Hi there, I've tried to use a different name, and it works now. What do you mean project names must be unique? unique in terms of the whole shuttle namespace or only my own project namespace?

Here is what I've tried:

<img width="712" alt="Screenshot 2023-07-21 at 9 23 58 AM" src="https://github.com/shuttle-hq/shuttle/assets/24603835/9831b86d-b435-4131-a786-0ff728b1eb25">

Then I run the command it suggests:

<img width="619" alt="Screenshot 2023-07-21 at 9 24 17 AM" src="https://github.com/shuttle-hq/shuttle/assets/24603835/e8fbea94-7906-4e74-b7ff-edc5ac282900">

Then I tried to specify the project name:

<img width="1009" alt="image" src="https://github.com/shuttle-hq/shuttle/assets/24603835/97358e3e-0c47-4663-a10b-102068785133">

**Comment by sparkyvxcx** [comment]
> Project names must be unique. If one does already exist, use a different one. Here are ways to modify which project name Shuttle uses: https://docs.shuttle.rs/configuration/shuttle-service-name


<img width="428" alt="image" src="https://github.com/shuttle-hq/shuttle/assets/24603835/6c099b13-6bf7-4ea3-b914-b36b6b5db360">

Okay, now I figure it out since the deployed project's URI consists of a subdomain from the project name, the project name needs to be globally unique. Thanks for your help!
