### ISSUE TITLE
[Bug]: failed to provision shuttle_shared_db

### ISSUE THREAD

**Issue by paul2t** [shuttle-hq/shuttle#1104]
### What happened?

I was following the authentication tutorial.
After the step "registering our database"
`cargo shuttle deploy` was working fine.
but not `cargo shuttle run`.

### Version

v0.21.0

### Which operating system(s) are you seeing the problem on?

Windows

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
ERROR cargo_shuttle::provisioner_server: got unexpected error while inspecting docker container: error trying to connect: The system cannot find the file specified. (os error 2)
ERROR cargo_shuttle: failed to load your service error="Custom error: failed to provision shuttle_shared_db :: Postgres"
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by joshua-mo-143** [comment]
Hey there, do you have Docker installed on your computer? 
Also, was it running at the time?

**Comment by paul2t** [comment]
Hi, thanks for the reply.
I do have docker installed.
It wasn't running at the time.
I just tested again after checking docker is not running, and I still have the same issue.
I also restarted my computer, checking that docker didn't start on boot, I also got the same error.

**Comment by TylerBloom** [comment]
This is also happening to me on Linux (Pop-OS). The same version number and CPU arch. I get the following error when running with and without docker installed and both running and not running:
```
2023-07-22T22:55:49.129967Z ERROR cargo_shuttle: failed to load your service error="Custom error: failed to provision shuttle_shared_db :: MongoDb"
```
I can deploy to Shuttle just fine, but local runs are not possible. This is what my entry point looks like:
```rust
#[shuttle_runtime::main]
async fn axum(
    #[shuttle_shared_db::MongoDb(local_uri = "mongodb://localhost:27017/")] db_conn: Database,
) -> shuttle_axum::ShuttleAxum {
```

**Comment by paul2t** [comment]
Oh, I understand now. I tested with docker started and it's working now.
Maybe the error message could be improved.
Something like "Docker not found". I didn't know it wanted to use docker.
I guess this is fixed for me now.
@TylerBloom You should try removing the local_uri and see if it creates the database automatically.

**Comment by oddgrd** [comment]
Indeed, the local_uri is for if you want to setup your own DB locally and have the local runner use that. If you don't have the local_uri set, the local run will automatically start a docker mongodb container for you.
