### ISSUE TITLE
Support Yew

### ISSUE THREAD

**Issue by mattheworris** [shuttle-hq/shuttle#1113]
Yew seems to be a popular front-end framework, it would be great to support it along side the other front-end options.

**Comment by jonaro00** [comment]
Hi Matthew,

Shuttle currently supports any front-end that compiles to static assets.
Trunk can compile Yew to such assets, and then you can use `shuttle-static-folder` to serve them.
The catch is that the building of the front-end assets now needs to be done *before* you deploy, but we are aiming to support more ways of building them at deploy time (such as Trunk).

There is no official example for how to set up a project with Yew yet, but there are some community efforts.
This is an example of a fullstack setup: https://github.com/TylerBloom/shuttle-fullstack-rust-example

**Comment by jonaro00** [comment]
Another alternative: https://github.com/sentinel1909/shuttle-template-yew

**Comment by sentinel1909** [comment]
> Another alternative: https://github.com/sentinel1909/shuttle-template-yew

I just pushed up what I think of as a reasonably complete MVP for this template. It seems to work nicely.

**Comment by mattheworris** [comment]
Excellent, thank you.

**Comment by sentinel1909** [comment]
Thinking this issue can be closed? I'm continuing to focus on using Yew as my frontend web framework of choice, so can take responsibility for it from a documentation/learning resources perspective.

**Comment by jonaro00** [comment]
There is more to build in regards to this, but the main point of this issue is addressed. Closing
