### ISSUE TITLE
[Feature]: Could cargo-shuttle auto-check if it's out of date?

### ISSUE THREAD

**Issue by beyarkay** [shuttle-hq/shuttle#1131]
### Describe the feature

Right now, it's kinda easy to miss a new release of the shuttle runtime (especially since they're coming hot and fast 🔥 ).

Would the team merge a PR that (somehow) checks the latest version of `cargo-shuttle` and if it's greater than the current `cargo-shuttle` version, recommends an update? We'd probably only want to do this when a network call is already being made.

### Suggestion or Example of how the feature would be used

So if the user types in a command that makes a network call (which would be most of them) `cargo-shuttle` would attempt to complete that command and then print out a message saying something like "Run this command to update shuttle":

```
$ cargo shuttle status

Service Name:  [******]
Deployment ID: [******]
Status:        running
Last Updated:  [******]
URI:           [******]

Run this command to update `cargo-shuttle` from v0.20.0 to v0.22.0:
cargo binstall cargo-shuttle
Or set SHUTTLE_NO_UPDATE_CHECK to disable these checks in the future.
```

Quite a few tools have something like this. Pip comes to mind:

<img width="507" alt="Screenshot 2023-08-04 at 18 56 35" src="https://github.com/shuttle-hq/shuttle/assets/33420535/b7bb2cde-6a9f-417d-8848-68f7b77fc385">

But I think [`atuin`](https://atuin.sh/docs/config#update_check) also has something similar.

I've also been bitten before when the runtime got an update, and all my deployment attempts failed with weird errors until I realized I needed to update.

I'm happy to work on the PR if the team would be interested in this.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by beyarkay** [comment]
Hey, wondering if there's any comment on this?

**Comment by oddgrd** [comment]
Hey @beyarkay, apologies for the radio-silence, we're still getting caught up after holidays. I think this is a great idea! Do you have a suggestion for where we will request the version of cargo-shuttle from? My first thought was putting it in the `gateway`, but it would be good if we could implement it in such a way that we did not need to update the `gateway` when we update `cargo-shuttle`. Currently we do update everything in lockstep, but that will change, and releasing the CLI on it's own can be useful.

**Comment by beyarkay** [comment]
No stress! I'm not entirely sure what the best place to put this would be, but I will have a look tomorrow morning to see what looks viable.

**Comment by oddgrd** [comment]
Hmm, perhaps we could just call the GitHub API and see if the latest release is a newer version than the current client? We could link to the release notes too, since upgrading might include more steps than just upgrading the CLI.
