### ISSUE TITLE
[Feature]: Crater for the shuttle runtime

### ISSUE THREAD

**Issue by beyarkay** [shuttle-hq/shuttle#1144]
### Describe the feature

From the rust-crater README:

> Crater is a tool to run experiments across parts of the Rust ecosystem. Its primary purpose is to detect regressions in the Rust compiler, and it does this by building a large number of crates, running their test suites and comparing the results between two versions of the Rust compiler.

This seems like the sort of tool which would be useful for the shuttle runtime for the same reasons as crater is useful for the `rustc`. Namely:

1. Many, many free and real-world test cases. Even the best devs can't write as much code as exist in the thousands of shuttle projects. 
2. Provide a guarantee to shuttle projects that minor-version releases won't break your build. I imagine this would be a hard requirement for people wanting to use shuttle for production.

While running every shuttle project might take too long and slow down development, compiling and deploying the top X% of shuttle projects would likely catch bugs and regressions before they make it to a minor version release. The exact percentage can be adjusted based on the delay this causes to the development cycle.

If there's interest in this, I'd be keen to open a PR/create a new repo to explore the idea.

### Suggestion or Example of how the feature would be used

This should be integrated with CI, and it might be possible to fork the existing infrastructure from [`rust-lang/crater`](https://github.com/rust-lang/crater) so that shuttle can benefit from the prior work done there.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by beyarkay** [comment]
Hey, wondering if there's any comment on this?

**Comment by oddgrd** [comment]
Hey, thanks for the suggestion! I think the end-result sounds great, but to me this seems like a very large undertaking, and I'm not sure we'd want to commit to it at this point. That said I can't immediately think of a reason that this wouldn't be *possible*, we do have metrics for project proxy hits, and it should be possible to extract the build files for these projects. In the near future (:crossed_fingers:) however, we will quite radically change how projects are built and deployed. There will no longer be one deployer container per project that builds, deploys and stores logs for projects. There will be an external build service that builds an image and sends them to another service to run and manage them. 

So I think the idea is worth considering, but I think we should wait either way until this refactor is complete. In the meantime, we do have a hole in our test suite when it comes to end-to-end testing. We have end-to-end tests in the `e2e` directory that are not ran regularly and they are often out-of-date. We also have some QA scripts for our CI, which don't work (you can see the runs of them in the `production` branch). We'll likely need to rethink/refactor both of these, so if you have any thoughts on that, we'd appreciate it (if you're interested, I know it's a bit of a segue from your issue :smile:)!

**Comment by beyarkay** [comment]
Yup definitely would be a large undertaking, totally understand that you're all focused on building out the core product at the moment. Definitely *not* worth building out infrastructure on top of something that's planned to change in the near future.

With regards to the e2e testing, I'm interested and will take a look, but [the other issue](https://github.com/shuttle-hq/shuttle/issues/1131#issuecomment-1681226395) seems like a better introduction to the shuttle codebase/architecture right now so I think I'll focus on that one for the moment.

I'll close the issue since it doesn't look like there'll be shuttle-crater in the near future. I've seen other projects use a GH label like `revisit-after-2023-11` to mark issues which aren't going to be looked at until after some dependency is met, in case you want the issue to be "partially" closed.
