### ISSUE TITLE
[Bug]: Static Folder updates

### ISSUE THREAD

**Issue by lasantosr** [shuttle-hq/shuttle#1146]
### What happened?

I'm using `#[shuttle_static_folder::StaticFolder(folder = "config")]` to load some config files in my project, which is a workspace with a single shuttle main.

I can see on the logs that the files are being packed in the root of the workspace.

I've tried to `cargo shuttle clean` and `cargo shuttle project reload` before the deploy but none of them seems to work, my app still reads some old values on startup. (i'm using `Figment`, if that helps)

### Version

v0.23.0

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
2023-08-10T17:50:28.252071Z DEBUG cargo_shuttle: Packing "/home/ubuntu/projects/shuttle/my-project/config/default.toml"
2023-08-10T17:50:28.252131Z DEBUG cargo_shuttle: Packing "/home/ubuntu/projects/shuttle/my-project/config/shuttle.toml
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by lasantosr** [comment]
I've just printed the folder hash just to verify

``` rust
#[shuttle_runtime::main]
async fn axum(
    #[shuttle_static_folder::StaticFolder(folder = "config")] config_folder: PathBuf,
) -> shuttle_axum::ShuttleAxum {
    let tree = merkle_hash::MerkleTree::builder(config_folder.as_os_str().to_string_lossy())
        .algorithm(merkle_hash::Algorithm::Blake3)
        .hash_names(false)
        .build()?;
    tracing::debug!(
        "The config folder '{}' hash: {:02X?}",
        config_folder.as_os_str().to_string_lossy(),
        tree.root.item.hash
    );
  ...
}
```

When I deploy the service, change some files on the config folder and deploy it again, the same hash is shown.

Running locally with `cargo shuttle run` (after copying the config file from the workspace root to the crate) works as expected, showing different hash each time a file is changed.

**Comment by joshua-mo-143** [comment]
Heya, I believe this issue is currently related to an ongoing issue with resources not updating on a re-deployment. We're working to make sure this gets fixed as soon as as feasible.

**Comment by joshua-mo-143** [comment]
Hey @lasantosr just as an fyi, we have pushed a new update that should fix this issue: https://github.com/shuttle-hq/shuttle/releases/tag/v0.24.0
