### ISSUE TITLE
[Bug]: can't deploy

### ISSUE THREAD

**Issue by williamlsh** [shuttle-hq/shuttle#1237]
### What happened?

Shuttle deploy stuck in "entering building state"

### Version

v0.25.1

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
INFO Entering building state
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
This may be related to #1201 and #1067, what does the output of your `cargo shuttle deployment list` look like? By the way, if you want more synchronous help with this, feel free to open a help thread in our [discord](https://discord.gg/shuttle).

**Comment by williamlsh** [comment]
> This may be related to #1201 and #1067, what does the output of your `cargo shuttle deployment list` look like? By the way, if you want more synchronous help with this, feel free to open a help thread in our [discord](https://discord.gg/shuttle).

I don't think it's related to these two issues. It's just stuck at `INFO Entering building state` forever and no error returns.

**Comment by iulianbarbu** [comment]
@williamlsh does `project restart` help before you try deploying again?

**Comment by williamlsh** [comment]
@oddgrd @iulianbarbu By the way, the shuttle project name is `meeting`.

**Comment by williamlsh** [comment]
It turns out to to be a mistake in configuring Shuttle project name, the target binary package name is different from that defined in `Shuttle.toml`.
