### ISSUE TITLE
[Bug]: My last name is not able to be used as the name for shuttle deploy

### ISSUE THREAD

**Issue by rhedgeco** [shuttle-hq/shuttle#1266]
### What happened?

So... this kind of situation is not new to me. My last name is `hedgecock`. Was excited to do some testing for my personal website for which I have my own server to deploy on with a domain name, but I was hoping to use shuttle.rs to test.

Well this is a tale as true as time for me. Unless this is a situation where `hedgecock` has happened to be a reserved word (I would be honored), the reason I'm getting errors is because my name contains "profanity". See relevant logs below.

### Version

v0.27.0

### Which operating system(s) are you seeing the problem on?

Linux, In deployment

### Which CPU architectures are you seeing the problem on?

x86_64, In deployment

### Relevant log output

```sh
[server] [Running 'cargo shuttle run']
[server] Error: Invalid global configuration file: /home/rhedgeco/Documents/projects/hedgecock-dev/server/Shuttle.toml
[server] 
[server] Caused by:
[server]     TOML parse error at line 1, column 8
[server]       |
[server]     1 | name = "hedgecock-dev"
[server]       |        ^^^^^^^^^^^^^^^
[server]     
[server]     `hedgecock-dev` is an invalid project name. project name must
[server]     1. start and end with alphanumeric characters.
[server]     2. only contain characters inside of the alphanumeric range, except for `-`, or `_`.
    3. not be empty.,
[server]     4. not contain profanity.
[server]     5. not be a reserved word.
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
Your suspicions are correct.
If you are doing a quick prototype, hopefully a different/modified name will be sufficient.
Otherwise, I would imagine that we could arrange special treatment for false-positives.
If you are planning to have a shuttle project, and point your own domain to it (will be possible in the Pro tier sooner or later), it does not matter much what the underlying project name is.

**Comment by rhedgeco** [comment]
Thanks for confirming my suspicions lol. looks like hedge.shuttleapp.rs will have to do
