### ISSUE TITLE
[Bug]: Crash after 'Moving built executable'

### ISSUE THREAD

**Issue by XChikuX** [shuttle-hq/shuttle#1267]
### What happened?

Bug happens in both the local build as well as deploying to shuttle.rs

Please have a look.

This is my project structure:
-root
|
  - Cargo.toml (members: shuttle, core)
  - /shuttle
    |
    - main.rs
    - Cargo.toml (depends on ../core)
| 
  - /core
    |
    - lib.rs
    - a bunch of other folders
    - Cargo.toml
 
 I get the compiled output in my target/release/<name_of_binary>
 
 However, I am not able to execute it with shuttle run ..
 

### Version

v0.27.0

### Which operating system(s) are you seeing the problem on?

Linux, In deployment

### Which CPU architectures are you seeing the problem on?

x86_64, In deployment

### Relevant log output

```sh
2023-09-21T22:45:09.613-07:00 [Deployer] test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.18s
2023-09-21T22:45:09.613-07:00 [Deployer] 
2023-09-21T22:45:09.619-07:00 [Deployer]  INFO shuttle_deployer::deployment::queue: Moving built executable
2023-09-21T22:45:09.619-07:00 [Deployer]  INFO Releasing queue slot
2023-09-21T22:45:09.621-07:00 [Deployer]  INFO Entering Crashed state
2023-09-21T22:45:09.621-07:00 [Deployer]  INFO Build failed
2023-09-21T22:45:09.621-07:00 [Deployer] ERROR shuttle_deployer::deployment::queue: {error="Internal I/O error: No such file or directory (os error 2)"} Service build encountered an error

Deployment crashed

Run the following for more details

cargo shuttle logs e42c5d81-eb36-4112-b57f-674f646db318
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
Hi @XChikuX, could you post the output of `RUST_LOG=cargo_shuttle cargo shuttle run`? You can remove lines if you want, I'm mainly interested in the debug messages and any errors.

**Comment by jonaro00** [comment]
Hmm, interesting.

Do you have the correct setup in your app, where the main function is tagged with `#[shuttle_runtime::main]`?

If yes:
Can you verify that the `/target/debug/trampoline-shuttle` file exists?
Is the project folder literally called `/root/serious_projects/trampoline`?

**Comment by XChikuX** [comment]
> Hmm, interesting.
> 
> Do you have the correct setup in your app, where the main function is tagged with `#[shuttle_runtime::main]`?

![image](https://github.com/shuttle-hq/shuttle/assets/5894493/03df3444-565d-438a-85e7-ffd3051d7449)


> If yes: Can you verify that the `/target/debug/trampoline-shuttle` file exists? Is the project folder literally called `/root/serious_projects/trampoline`?

Yes it is. There is no trampoline-shuttle file. There is only a trampoline binary, as there should be.

**Comment by jonaro00** [comment]
Ok.
Could it be that it is finding the wrong crate name, and therefore the wrong binary name?
Should the binary from the `shuttle` crate not be called `shuttle`? I'm wondering where the `trampoline-shuttle` and `trampoline` names are coming from. You don't have a `[[bin]]` section in any of the Cargo.toml's, right?

**Comment by jonaro00** [comment]
For example, in [this project](https://github.com/jonaro00/pixel-skribbl), I have a similar setup, and on `cargo shuttle run`, it correctly compiles and executes the binary called `backend`, since it is the single binary in the `backend` crate.

**Comment by XChikuX** [comment]
> Ok. Could it be that it is finding the wrong crate name, and therefore the wrong binary name? Should the binary from the `shuttle` crate not be called `shuttle`? I'm wondering where the `trampoline-shuttle` and `trampoline` names are coming from. You don't have a `[[bin]]` section in any of the Cargo.toml's, right?

I do in fact. 

**In my shuttle directory**
```
[package]
name = "trampoline-shuttle"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "trampoline"
path = "src/main.rs"
```

I removed `[[bin]]` and it works now..
What difference did it make? I've added it without the full understanding, behind why it's used.

I don't notice a different `trampolin-shuttle` or `shuttle` binary between either of my builds.

**Comment by jonaro00** [comment]
Without the `[[bin]]` entry, the binary will be named the same as the crate name, which is what Shuttle assumes you do. With it, and if it's pointing to the `src/main.rs` file, you are essentially renaming this default name of the binary.

**Comment by XChikuX** [comment]
Is it a good idea for shuttle to parse the toml file to make this seemless for the user?
Or are there complexities associated with it?

**Comment by XChikuX** [comment]
PS: Closing this..

**Comment by jonaro00** [comment]
If you have multiple binaries defined, Shuttle would not know which one to run. Therefore, we currently have the constraint of having to use the default binary. It is technically possible to pass args and/or parse this, but it is not worth the effort at the moment.
