### ISSUE TITLE
Discord Invite Invalid [Bug]: 

### ISSUE THREAD

**Issue by pdavidow** [shuttle-hq/shuttle#1282]
### What happened?

A bug happened! Discord gives me: Invite Invalid

### Version

n/a

### Which operating system(s) are you seeing the problem on?

Windows

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
Here is a permanent invite link: https://discord.gg/shuttle
Where did you find the invalid invite link?

**Comment by pdavidow** [comment]
Doesn't help.
![shuttle](https://github.com/shuttle-hq/shuttle/assets/220924/76cc212b-4e26-4605-bf72-07d398c76a5e)

**Comment by jonaro00** [comment]
It could be that your Discord account needs to have its email address verified.

**Comment by pdavidow** [comment]
I tried it again, and it worked now (without verifying email).
:)
