### ISSUE TITLE
[Bug]: thread 'main' panicked at 'shuttle-runtime version should be in the `name version` format'

### ISSUE THREAD

**Issue by Mouwrice** [shuttle-hq/shuttle#1285]
### What happened?

When trying to run `cargo shuttle run` locally I get the following panic:

```
thread 'main' panicked at 'shuttle-runtime version should be in the `name version` format', cargo-shuttle/src/lib.rs:1662:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Despite having both `shuttle-runtime = 0.27.0` in my Cargo.toml and `cargo shuttle --version`
outputting `cargo-shuttle 0.27.0`.

### Version

v0.27.0

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
stack backtrace:
   0:     0x560258f8a260 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf014552b94f53b0b
   1:     0x560258fb79af - core::fmt::write::hd931ce1f65786f99
   2:     0x560258f82407 - std::io::Write::write_fmt::h6a6fd63a04e82ec7
   3:     0x560258f8a065 - std::sys_common::backtrace::print::h1e42468794e7b82c
   4:     0x560258f6d961 - std::panicking::default_hook::{{closure}}::hbe45423b43205803
   5:     0x560258f6d5ff - std::panicking::default_hook::h84640917dec96f40
   6:     0x560258f6de09 - std::panicking::rust_panic_with_hook::h3f828bf7de94854a
   7:     0x560258f8a547 - std::panicking::begin_panic_handler::{{closure}}::h1494d1b7b833ecd5
   8:     0x560258f8a336 - std::sys_common::backtrace::__rust_end_short_backtrace::hfb56cb4321fb1fc8
   9:     0x560258f6db32 - rust_begin_unwind
  10:     0x56025815d533 - core::panicking::panic_fmt::h69ad0a157a771ebb
  11:     0x56025815d473 - core::option::expect_failed::h758520829348269a
  12:     0x56025841bdad - cargo_shuttle::check_version::h672ed8793c569212
  13:     0x560258188ff8 - cargo_shuttle::Shuttle::spin_local_runtime::{{closure}}::hf11e0ecedebd5502
  14:     0x5602581b00b7 - <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::hf90a10ebb34f983e
  15:     0x56025827ef43 - cargo_shuttle::Shuttle::local_run::{{closure}}::hd119e6f4d8e9418a
  16:     0x560258271adf - cargo_shuttle::Shuttle::run::{{closure}}::h2021a100170058ee
  17:     0x56025828f8e5 - tokio::runtime::park::CachedParkThread::block_on::he3cb173dcf978f67
  18:     0x5602583426f1 - cargo_shuttle::main::h6c2a1dc85315c5e3
  19:     0x560258324403 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha58e446f40302242
  20:     0x560258324cad - std::rt::lang_start::{{closure}}::hee716f358a627e5f
  21:     0x560258f62357 - std::rt::lang_start_internal::hbcbc84fca12d560d
  22:     0x560258342965 - main
  23:     0x7f8927d1eace - __libc_start_call_main
  24:     0x7f8927d1eb89 - __libc_start_main@@GLIBC_2.34
  25:     0x56025815dc45 - _start
  26:                0x0 - <unknown>
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
Thanks for reporting.

Some follow up questions for finding the issue:
- Is your project a single crate or in a workspace?
- Does your main function have the `#[shuttle_runtime::main]` attribute?
- If you do a plain `cargo run`, do you get an error beginning with "Runtime received malformed..."?

**Comment by Mouwrice** [comment]
Hi, thanks for your swift response!

I was using Nixos and Nix at the time, which do some non-traditional things which seems to make it unable for shuttle to properly find where it was installed, or something. I am by no means an expert in Nix, so someone with the experience could probably easily solve my problem. 

I have departed Nixos and Nix, since I do not have the time and commitment to become proficient in that interesting but difficult to learn OS and package manager. Anyway, I'm on EndeavourOS now (*i use arch btw* :upside_down_face:) and it all just works flawlessly!

Sorry to bother you. I have just been getting into shuttle and it just so simple and nice to have, so thanks a lot!

From my part the issue can be closed

**Comment by jonaro00** [comment]
Nice to hear that. Yeah, Nix seems very complex. A blessing and a curse is that we are trying to involve Nix in our upcoming builder refactoring. We'll see how that goes :sweat_smile:
