### ISSUE TITLE
[Improvement]: Consider if migrating to `tower-sessions` is appropriate

### ISSUE THREAD

**Issue by maxcountryman** [shuttle-hq/shuttle#1288]
### Describe the improvement

Hi folks,

I'm the author of `axum-sessions`, which is a crate I see you all are using--I'm glad to see you've found it useful!

Over the course of the last year or so we've hit some roadblocks with our key dependency, `async-session`. The long and short of that is in order to unblock that and address some problems with `axum-sessions`'s design, we've released a new crate which aims to replace `axum-sessions`: [`tower-sessions`](https://github.com/maxcountryman/tower-sessions).

`tower-sessions` no longer relies on a third-party crate for its session implementation and this has allowed us to change its design to better fit `tower` and the broader `tower` ecosystem (i.e. `axum`). For instance, we no longer need writable and readable sessions, and have simplified the interface as a result.

I'd be curious if there's interest in migrating and am happy to help if so.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by oddgrd** [comment]
Hey @maxcountryman, thanks for opening this issue and for offering to help in implementing this change. I think the new crate looks good, and I think it's great that you designed it around `tower`! The reason we didn't accept this issue yet, is that we don't currently use the sessions flow in our `auth` service (which is what uses `axum-sessions`). We might do so in the future, though, we just need to discuss this a bit internally. We'll get back to you when we have an answer. Thanks again!

**Comment by oddgrd** [comment]
Hello again @maxcountryman! We have decided to fully remove our sessions code from the backend, so we will close this ticket for now. If we start using sessions on the backend again in the future, we'll consider using your crate. Thanks!
