### ISSUE TITLE
[Feature]: Add a shuttle-admin command to invalidate gateway auth cache

### ISSUE THREAD

**Issue by iulianbarbu** [shuttle-hq/shuttle#1306]
### Describe the feature

Doing a release just for the auth service can be disruptive since the gateway service stores a cache for auth tokens, which might not be able to be decoded (TODO: explain why) after an auth service restart. We want to be able to invalidate the gateway auth cache and not impact users when trying to execute commands after an auth release.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by jonaro00** [comment]
@iulianbarbu This can be closed now that we persist the auth key right?

**Comment by iulianbarbu** [comment]
Thanks for the ping. You're right. Closing this.
