### ISSUE TITLE
[Feature]: auto reload

### ISSUE THREAD

**Issue by dev-ardi** [shuttle-hq/shuttle#1308]
### Describe the feature

something like `cargo shuttle watch` that rebuilds the project on file changes

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by jonaro00** [comment]
Hi. We have an issue tracking this: https://github.com/shuttle-hq/shuttle/issues/496
There are also some docs on how to use external tools until this gets official support: https://docs.shuttle.rs/getting-started/local-run#live-reload-backend-with-cargo-watch

**Comment by dev-ardi** [comment]
I didn't find it. My bad!
