### ISSUE TITLE
[Improvement]: `--raw` parameter for commands that print tables

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1315]
### Describe the improvement

Currently, the commands `cargo shuttle project list` and `cargo shuttle deployment list` show their output in unicode character tables.
![image](https://github.com/shuttle-hq/shuttle/assets/54029719/83b0f06c-4071-407b-bbcc-220e774d60be)

This can be annoying when scripting or when trying to copy a value on a narrow terminal.
The task is to add a `--raw` flag to these commands that prints the tables with space-aligned columns, similar to `docker ps`. An important difference is that the cell width should not be affected by terminal width.

[Bonus task (super easy)]: Change the default value of `project list`'s limit argument to 15.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by reubenwong97** [comment]
Could you provide an example of the output desired? Just want to be clear on what this space-aligned table would look like.

**Comment by supleed2** [comment]
The `docker ps` example in the [docker docs](https://docs.docker.com/engine/reference/commandline/ps/) looks like this:

```shell
docker ps --no-trunc

CONTAINER ID                                                     IMAGE                        COMMAND                CREATED              STATUS              PORTS               NAMES
ca5534a51dd04bbcebe9b23ba05f389466cf0c190f1f8f182d7eea92a9671d00 ubuntu:22.04                 bash                   17 seconds ago       Up 16 seconds       3300-3310/tcp       webapp
9ca9747b233100676a48cc7806131586213fa5dab86dd1972d6a8732e3a84a4d crosbymichael/redis:latest   /redis-server --dir    33 minutes ago       Up 33 minutes       6379/tcp            redis,webapp/db
```

Ignoring any width info from the terminal. I guess it would look similar with the terminal wrapping the output and no escape codes (colouring) so that it's easier to work with, eg. piping to other commands.

**Comment by supleed2** [comment]
I have a working version of this because I got distracted when I got stuck on #962. I'll open a draft PR for now.
