### ISSUE TITLE
[Improvement]: Remove pin to version 0.30.1 of libsql-client in Shuttle Turso

### ISSUE THREAD

**Issue by sentinel1909** [shuttle-hq/shuttle#1324]
### Describe the improvement

Per the discussion yesterday on Discord, I understand that it's no longer necessary to pin the version of libsql-client to version 0.30.1.

I will remove the pin and move libsql-client to version 0.32.0 in the Cargo.toml of the Shuttle Turso crate.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by oddgrd** [comment]
It would be great if you could make the required changes to the examples and the docs as well!
