### ISSUE TITLE
[Feature]: Expose connection string from shared db

### ISSUE THREAD

**Issue by mangelarilla** [shuttle-hq/shuttle#1346]
### Describe the feature

Expose the connection string of the shared database to allow interoperability with other crates, like Fang. 

### Suggestion or Example of how the feature would be used

As the `PgConnectOptions` struct is already exposed in the pool, but with no public properties. Maybe make it implement `ToString`, `Display` or a new method `.connection_string()` to make the conversion.

Not sure if there's control over this struct, or it is `sqlx` crate responsability.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by jonaro00** [comment]
I think the suggestion of getting the string in an easy way is good.

If you look at how the shared db plugin works under the hood (https://github.com/shuttle-hq/shuttle/blob/main/resources/shared-db/src/postgres.rs), you can make your own copy that suits your needs.
This is essentially what @joshua-mo-143 did in https://github.com/joshua-mo-143/shuttle-fang/blob/main/src/lib.rs
