### ISSUE TITLE
[Improvement]: rocket v0.5.0-rc.4

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1363]
### Describe the improvement

New rc version of rocket was released, with some breaking changes. We want to update all of the following to use the new version, and resolve any breaking changes to make everything work:

- `shuttle-rocket` (this repo)
- rocket examples (https://github.com/shuttle-hq/shuttle-examples/tree/main/rocket)
- rocket examples that are replicated on the docs (https://docs.shuttle.rs/examples/rocket)

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by sentinel1909** [comment]
I'll take a stab at tackling this one.

**Comment by orhun** [comment]
You got it! @sentinel1909
