### ISSUE TITLE
[Bug]: show-secrets replaces shared DB URL

### ISSUE THREAD

**Issue by Friendly-Banana** [shuttle-hq/shuttle#1367]
### What happened?

`cargo-shuttle resource list` prints `…project:********@db.shuttle.rs:5432/…`
The password is correctly redacted. 
`cargo-shuttle resource list --show-secrets` doesn't just show the password, it also yields another host, which makes it impossible to simply copy the URL: 
`…project:password@postgres:5432/…`

Why is `db.shuttle.rs` replaced with `postgres`?

### Version

0.31.0

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
$ cargo-shuttle resource list
postgres://user-project:********@db.shuttle.rs:5432/db-project

$ cargo-shuttle resource list --show-secrets
postgres://user-project:password@postgres:5432/db-project
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
Thanks for the report! This was resolved in https://github.com/shuttle-hq/shuttle/pull/1368 and released in 0.32.0.
