### ISSUE TITLE
[Improvement]: Generate manpage with `clap-mangen` for `cargo-shuttle`

### ISSUE THREAD

**Issue by orhun** [shuttle-hq/shuttle#1377]
### Describe the improvement

We use [`clap`](https://crates.io/crates/clap) for parsing the command-line arguments for `cargo-shuttle`. We can also integrate [`clap-mangen`](https://crates.io/crates/clap-mangen) for generating a manpage. I see two ways of doing this:

- have a separate binary (`cargo-shuttle-mangen`) (see [this](https://github.com/orhun/halp/blob/main/src/bin/mangen.rs) example)
- use the build script (see [this](https://github.com/orhun/kmon/blob/master/build.rs) example)

Here's why having a manpage is good:

> Having a man page is advantageous because it serves as local and offline documentation for commands or programs, offering users quick and standardized access to crucial information. Its consistency, comprehensive details, and integration with the command line make it a valuable resource for understanding and utilizing software effectively. The accessibility of man pages promotes inclusivity and facilitates scripting and automation, contributing to an enhanced user experience in various computing environments.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by selectiveduplicate** [comment]
Hello. Is this issue still open? I was hoping to give it a shot.
Have we decided on the approach?

**Comment by orhun** [comment]
Hello @selectiveduplicate, yes it is still open! I think we can go with the binary approach.

**Comment by selectiveduplicate** [comment]
> Hello @selectiveduplicate, yes it is still open! I think we can go with the binary approach or alternatively we can have a flag to generate it. (similar to `cargo shuttle generate`)

Yeah a sub-command for `cargo shuttle` like `cargo shuttle manpage` can do. IMO that sounds better than the binary approach. So as far as I understand I need to start by adding a new field `ManPage` (feel free to suggest a better name :sweat_smile:) in the [`Command` struct](https://github.com/shuttle-hq/shuttle/blob/22f512e5553b9ab34d48b3f0222a00d94c4699f6/cargo-shuttle/src/lib.rs) and then putting the corresponding functionality in [`lib.rs`](https://github.com/shuttle-hq/shuttle/blob/22f512e5553b9ab34d48b3f0222a00d94c4699f6/cargo-shuttle/src/lib.rs)?

**Comment by orhun** [comment]
Exactly, sounds good. We can simply go with `cargo shuttle manpage`, or even better, we can do:

```sh
$ cargo shuttle generate --shell bash # generates shell completions

$ cargo shuttle generate --manpage # generates manpage (cargo-shuttle.1)
```

This means making the `--shell` argument optional and adding a custom logic to lib.rs but I think it is much cleaner than adding a new subcommand.

**Comment by selectiveduplicate** [comment]
Yeah that's much better! Thanks.

**Comment by orhun** [comment]
No worries, let me know if you need help/guidance with anything!
