### ISSUE TITLE
[Improvement]: Support a short argument for `--working-directory`

### ISSUE THREAD

**Issue by orhun** [shuttle-hq/shuttle#1381]
### Describe the improvement

Typing out `--working-directory` every time that I want to do `cargo shuttle run` is annoying so I propose we support a short argument/alias such as `-w`

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by oddgrd** [comment]
@jonaro00 implemented this a while back, you can use `cargo shuttle run --wd ...`. :smile:

**Comment by orhun** [comment]
It is not visible in the help output though:

```
$ cargo shuttle run -h
Run a Shuttle service locally

Usage: cargo-shuttle run [OPTIONS]

Options:
  -p, --port <PORT>
          Port to start service on [env: PORT=] [default: 8000]
      --working-directory <WORKING_DIRECTORY>
          Specify the working directory [default: .]
```

**Comment by oddgrd** [comment]
Oh, indeed! :sweat_smile: We can make it visible with [visible_alias](https://docs.rs/clap/latest/clap/struct.Arg.html#method.visible_alias).
