### ISSUE TITLE
[Improvement]: Bump base64 dependency

### ISSUE THREAD

**Issue by orhun** [shuttle-hq/shuttle#1393]
### Describe the improvement

We are using `base64` dependency for auth tests and the version is outdated:

https://github.com/shuttle-hq/shuttle/blob/299a30db5b3361c328b3231971d8276d10995be7/Cargo.toml#L47

The tests can be run like this:

```sh
cargo test -p shuttle-common
```

The moral of the story is we can bump it but there are some breaking changes: https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md#0200

Feel free to comment on this issue if you want to work on it!

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by cassie-rust** [comment]
I'll gladly take a look, but if someone else submits a PR I'm not going to be like, offended. I've not contributed to open source before, so this'll be a nice first attempt I guess?

**Comment by jonaro00** [comment]
@cassie-rust Thanks for showing interest! I can assign you to this. I think it's a great issue for first-timers. If you need help with how to handle forking/branch/PR, feel free to ask. You can join the Discord contributors channel if you want even faster responses :) .

**Comment by orhun** [comment]
@cassie-rust go ahead!
