### ISSUE TITLE
[Improvement]: Unify service doc comments and crate docs with README files

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1395]
### Describe the improvement

Our service crates' documentations were recently updated so that the crate documentation
```rs
//! Shuttle service integration for the Axum web framework.
//!
//! ## Example
//!
//! ```rust,no_run
//! use axum::{routing::get, Router};
//!
//! async fn hello_world() -> &'static str {
//!     "Hello, world!"
//! }
//!
//! #[shuttle_runtime::main]
//! async fn axum() -> shuttle_axum::ShuttleAxum {
//!     let router = Router::new().route("/", get(hello_world));
//!
//!     Ok(router.into())
//! }
//! ```
```
is very similar to the return type's documentation
```rs
/// Return type from the `[shuttle_runtime::main]` macro for a Axum-based service.
///
/// ## Example
///
/// ```rust,no_run
/// use axum::{routing::get, Router};
///
/// async fn hello_world() -> &'static str {
///     "Hello, world!"
/// }
///
/// #[shuttle_runtime::main]
/// async fn axum() -> shuttle_axum::ShuttleAxum {
///     let router = Router::new().route("/", get(hello_world));
///
///     Ok(router.into())
/// }
/// ```
```

It would be better to only have one unified version of this doc in the crate's README.md file, and use `#![doc = include_str!("../README.md")]` and `#[doc = include_str!("../README.md")]` on the crate and the return type respectively.

This can be done for every service in the `services/` dir.

---

Bonus task: Update the Cargo package descriptions if needed

--- 

Feel free to comment on this issue if you want to work on it!

**Comment by AvaterClasher** [comment]
Can i do this ?

**Comment by jonaro00** [comment]
Go for it! @AvaterClasher
