### ISSUE TITLE
[Improvement]: Better error message when project is not found in gateway

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1397]
### Describe the improvement

To improve the error message "project not found" to something like "project 'blablah' not found", it needs a little refactor.
Start with turning `ProjectNotFound` into a tuple struct `ProjectNotFound(ProjectName)`.

Then, go through all usages of this variant, and add the project name into it:
- In ScopedUser extractor, its local variable is called `scope`.
- The 3 usages of ProjectNotFound in gateway's `proxy.rs` can be handled like this:
  - 1st one: Replace with BadHost
  - 2nd one: Replace with InvalidProjectName
  - 3rd one: Replace with CustomDomainNotFound
- The rest should be straight forward.

After this change, calling `cargo r -p cargo-shuttle -- project status --name unusedprojectname` against the local stack should give the project name back in the error.

---

Feel free to comment on this issue if you want to work on it!

**Comment by selectiveduplicate** [comment]
Hi! I'd like to work on this one if that's okay.

**Comment by orhun** [comment]
Sure, go ahead @selectiveduplicate!
