### ISSUE TITLE
Doc: Updating Twitter's Old Name to New Name in README.md Community and Support Section

### ISSUE THREAD

**Issue by BandhiyaHardik** [shuttle-hq/shuttle#1400]
I was looking into the shuttele repository for exploration during that time i noticed that the badge is updated to new one but in community and support section it is still old name.

# Screenshots:
### Badge is updated 
![image](https://github.com/shuttle-hq/shuttle/assets/110784317/ab258fd8-f58e-4942-a1f7-96f136da5fe5)

### Currently Community and Support Section in README.md
![image](https://github.com/shuttle-hq/shuttle/assets/110784317/354b235d-53a4-43ed-bf70-9436265a6fa1)

### Expected Community and Support Section in README.md
![image](https://github.com/shuttle-hq/shuttle/assets/110784317/8cb307ff-1743-4b8e-80a7-c16e98904103)

**Comment by BandhiyaHardik** [comment]
I would like to work on this issue

**Comment by orhun** [comment]
Sounds reasonable, go ahead!
