### ISSUE TITLE
[Bug]: Feature flag "axum-0-7" fails to build

### ISSUE THREAD

**Issue by timredd** [shuttle-hq/shuttle#1443]
##  Summary
Enabling the `"axum-0-7"` feature flag that was recently added to resolve a [compatibility issue stemming from Axum 0.7.1](https://github.com/shuttle-hq/shuttle/issues/1438) causes compilation to fail with `E0252: two items of the same name cannot be imported without rebinding one of the items under a new local name`.

## Steps to reproduce:
1. Run `cargo shuttle init --template axum`.
2. Update `axum` from 0.6.20 to 0.7.1 in `Cargo.toml`.
3. Enable `shuttle-axum` feature flag `"axum-0-7"` in `Cargo.toml`.
4. Attempt to compile the project.
5. Observe an `E0252` compilation error.

### Version

v0.34.1

### Which operating system(s) are you seeing the problem on?

macOS

### Which CPU architectures are you seeing the problem on?

ARM64

### Relevant log output

```sh
| # ./shuttle-axum-0.34.1/src/lib.rs:25:5
   |
23 | use axum::Router;
   |     ------------ previous import of the type `Router` here
24 | #[cfg(feature = "axum-0-7")]
25 | use axum_0_7::Router;
   |     ^^^^^^^^^^^^^^^^ `Router` reimported here
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
Hey @timredd! :wave: Did you also declare default features as false? 0.6 is still the default, we'll change that as 0.7 matures. This is what it should look like:
`shuttle-axum = { version = "0.34.1", default-features = false, features = ["axum-0-7"] }`

**Comment by jonaro00** [comment]
Axum 0.7 is now the default from shuttle 0.36.0 and onwards. Check the release notes for how to use 0.7 or stay on 0.6: https://github.com/shuttle-hq/shuttle/releases/tag/v0.36.0
