### ISSUE TITLE
[Bug]: Internal server error :"Kind: SCRAM failure: Authentication failed., labels: {}"

### ISSUE THREAD

**Issue by LigeronAhill** [shuttle-hq/shuttle#1469]
### What happened?

When trying to connect to the shared mongodb got this: Internal server error :"Kind: SCRAM failure: Authentication failed., labels: {}"
Tried deleting the database and deleting the project, nothing works.
Mongo remains in the resources, the project is not deleted, it says - contact support.
Deleting DB:

WARNING:
    Are you sure you want to delete this project's database::shared::mongodb?
    This action is permanent.
✔ Are you sure? · yes
Error: 404 Not Found
Message: resource not found, try running `cargo shuttle deploy`

Deleting project:
Error: 500 Internal Server Error
Message: Could not automatically delete the following resources: database::shared::mongodb. Please reach out to Shuttle support for help.
### Version

v0.34.1

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
Internal server error :"Kind: SCRAM failure: Authentication failed., labels: {}"
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
Hey @LigeronAhill, apologies for the delayed response. Was your deployment unable to connect, or were you unable to connect to it directly? If it's the latter, being unable to connect directly to the shared mongodb database is a known limitation of this resource. It's a consequence of very strict auth settings to make it impossible for tenants to access other tenants databases. But we should document this limitation before closing this ticket.

**Comment by jonaro00** [comment]
Closing due to being irrelevant on the shuttle.dev platform.
