### ISSUE TITLE
[Improvement]: Don't pull in axum 0.6 when trying shuttle-axum feature 'axum-0-7'

### ISSUE THREAD

**Issue by TClasen-Foxit** [shuttle-hq/shuttle#1474]
### Describe the improvement

updating a project to use axum 0.7, using ```shuttle-axum = { version = "0.35.0", default-features = false, features = ["axum-0-7"], optional = false }```, unfortunately still adds axum 0.6 through the transitive ```shuttle-runtime``` and  its own ```shuttle-common``` dependency. I couldn't find a way to disable this by disabling default and optional features on common/runtime.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by TClasen-Foxit** [comment]
I looked into it and it looks like this cannot be avoided at the moment as axum seems to be a necessary dependency of shuttle-common itself. I guess this will be fixed once shuttle has been itself updated to axum 0.7

**Comment by jonaro00** [comment]
@TClasen-Foxit That's correct. Thanks for raising the concern. 
Even after we upgrade to 0.7 we would still need https://github.com/hyperium/tonic/pull/1583 (and maybe some more). A waiting game :)
