### ISSUE TITLE
[Improvement]: Use testcontainers to spawn postgres docker containers in integration tests

### ISSUE THREAD

**Issue by iulianbarbu** [shuttle-hq/shuttle#1479]
### Describe the improvement

A few of our services (logger, provisioner & soon auth) integration tests are using a postgres instance in a docker container, communicating with it to exercise their business logic in the context of integration tests. We'd like to not maintain test logic that sets up a postgres Docker container, but use instead testcontainers [1].

Definition of done:
* use testcontainers to spawn the postgres docker instance where needed
* provide APIs to get unique connection strings bound to unique databases, that can be used by test cases in parallel if needed
* Ensure the postgres instance container is removed at the end of the test cases
* Ensure the postgres instance container is returned only after it is ready to serve requests
* ideally, split the work into separate PRs (one per service, where the first one will contain the testcontainers-related changes too).

[1] https://docs.rs/testcontainers/latest/testcontainers/#:~:text=The%20testcontainers%20ecosystem%20facilitates%20self,actual%20database%20to%20be%20present.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by jonaro00** [comment]
I attempted this recently, but it causes dependency conflicts on bollard-stubs. When gateway is no longer using bollard, it might work (c-s will still use it).

**Comment by jonaro00** [comment]
testcontainers are being used in the new backend :rocket:
