### ISSUE TITLE
[Feature]: Windows Powershell install script

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1496]
### Describe the feature

Make a Windows cousin for the Linux/Mac [install script](https://github.com/shuttle-hq/shuttle/blob/main/install.sh).

You can take inspiration from the mentioned installer and other projects that have PS install scripts to create a script that does the same high level things:
- Attempt to install with cargo-binstall if it exists
- Attempt to download a binary from github
- Install with cargo install
  -  Offer to install Rust via rustup if cargo is not found

### Suggestion or Example of how the feature would be used

For example, `iwr https://[url-to-script] -useb | iex`

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by supleed2** [comment]
Hey @sentinel1909, 8bit from the discord. I've pretty quickly hacked this together, any improvements you can think of? It's pretty heavily based on [cargo-binstall's install script](https://github.com/cargo-bins/cargo-binstall/blob/main/install-from-binstall-release.ps1).

Also I don't think the bash script includes installing rust but I might've just missed it, added to this one anyway.

@jonaro00 Should `cargo-binstall` be stopped from installing from source, so that downloading the binary is preferred? I went with no, because downloading the binary doesn't add it to cargo's list of installed binaries, and then you can't do `cargo uninstall`.

<details>
<summary>`install.ps1` Script</summary>

```powershell
$ErrorActionPreference = "Stop"

if (Get-Command -CommandType Application -ErrorAction SilentlyContinue cargo-binstall.exe) {
	Write-Host "Installing cargo-shuttle using cargo binstall"
	cargo-binstall.exe cargo-shuttle
	if ($?) {
		Write-Host "cargo-shuttle installed" -ForegroundColor Green
		[Environment]::Exit(0)
	}
	else {
		Write-Host "Could not install from release using cargo binstall, trying manual binary install" -ForegroundColor Red
	}
}
else {
	Write-Host "cargo binstall not found, trying manual binary install" -ForegroundColor Red
}

$CargoHome = if ($null -ne $Env:CARGO_HOME) { $Env:CARGO_HOME } else { "$HOME\.cargo" }
$RepoUrl = "https://github.com/shuttle-hq/shuttle"
$TempDir = $Env:TEMP
$Arch = [Environment]::GetEnvironmentVariable("PROCESSOR_ARCHITECTURE", [EnvironmentVariableTarget]::Machine)
if (($Arch -eq "AMD64") -and (Get-Command -CommandType Application -ErrorAction SilentlyContinue tar.exe)) {
	(Invoke-WebRequest "$RepoUrl/releases/latest" -Headers @{ "Accept" = "application/json" }).Content -match '"tag_name":"([^"]*)"' | Out-Null
	$LatestRelease = $Matches.1
	$BinaryUrl = "$RepoUrl/releases/download/$LatestRelease/cargo-shuttle-$LatestRelease-x86_64-pc-windows-msvc.tar.gz"
	Invoke-WebRequest $BinaryUrl -OutFile "$TempDir\cargo-shuttle.tar.gz"
	New-Item -ItemType Directory -Force "$TempDir\cargo-shuttle"
	tar.exe -xzf "$TempDir\cargo-shuttle.tar.gz" -C "$TempDir\cargo-shuttle"
	Move-Item "$TempDir\cargo-shuttle\cargo-shuttle-x86_64-pc-windows-msvc-$LatestRelease\cargo-shuttle.exe" "$CargoHome\bin\cargo-shuttle.exe"
	Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$TempDir\cargo-shuttle.tar.gz", "$TempDir\cargo-shuttle"
	Write-Host "cargo-shuttle installed" -ForegroundColor Green
	[Environment]::Exit(0)
}
elseif ($Arch -ne "AMD64") {
	Write-Host "Unsupported Architecture: Binaries are not currently built for $Arch, skipping manual binary install" -ForegroundColor Red
}
else {
	Write-Host "tar.exe not found, skipping manual binary install" -ForegroundColor Red
}

if (Get-Command -CommandType Application -ErrorAction SilentlyContinue cargo.exe) {
	cargo.exe install cargo-shuttle --locked
	if ($?) {
		Write-Host "cargo-shuttle installed" -ForegroundColor Green
		[Environment]::Exit(0)
	}
	else {
		Write-Host "Could not install cargo-shuttle using cargo" -ForegroundColor Red
		[Environment]::Exit(1)
	}
}
else {
	if ($Arch -in "AMD64", "x86") {
		Write-Host "cargo.exe not found" -ForegroundColor Red
		$Confirm = Read-Host -Prompt "Would you like to install Rust via Rustup? [y/N]"
		if ($Confirm -notin "y", "yes") {
			Write-Host "Skipping rustup install, cargo-shuttle not installed"
			[Environment]::Exit(1)
		}
		$RustupUrl = if ($Arch -eq "AMD64") { "https://win.rustup.rs/x86_64" } else { "https://win.rustup.rs/i686" }
		Invoke-WebRequest $RustupUrl -OutFile "$TempDir\rustup.exe"
		& "$TempDir\rustup.exe" toolchain install stable
		if ($?) {
			Remove-Item -ErrorAction SilentlyContinue "$TempDir\rustup.exe"
			Write-Host "Rust installed via Rustup, please re-run this script" -ForegroundColor Green
			[Environment]::Exit(0)
		}
		else {
			Remove-Item -ErrorAction SilentlyContinue "$TempDir\rustup.exe"
			Write-Host "Rust install via Rustup failed, please install Rust manually" -ForegroundColor Red
			[Environment]::Exit(0)
		}
	}
	else {
		Write-Host "cargo.exe not found, rustup only supports x86 and x86_64, please install Rust manually" -ForegroundColor Red
		[Environment]::Exit(1)
	}
}
```
</details>

**Comment by jonaro00** [comment]
@supleed2 binstall will find the best way to do it, so a manual download or a manual install are just fallbacks. Looks like a good start. I don't think the inability to uninstall a manual download is anything to worry about.

The bash script does ask for installing rust if cargo is not found.

You can also copy over the "logo" and links and such from the bash script :)

**Comment by sentinel1909** [comment]
@supleed2 Looks awesome! I'm just getting what you've done into a branch so we can continue on from a common point. I think that's the best way to carry on?  Someone let me know if I'm off base...

**Comment by jonaro00** [comment]
Sounds good. A file in the root of the repo called `install.ps1` is a suitable location.

**Comment by sentinel1909** [comment]
Sorry guys, very stupid question...I've created and pushed up a branch to my Shuttle repo, how do I link it here?  Just open a PR like usual or do I invite @supleed2 to my branch?

**Comment by jonaro00** [comment]
They way I've done it is: Do it as you normally would, but invite 8bit as a collaborator to your fork. This gives him write access to the branch that you make your PR from.
Not sure if there is a more optimal way but I know that this works.

**Comment by supleed2** [comment]
I've added the logo/links text to the branch, feel free to open the PR after you've gone over it @sentinel1909

**Comment by sentinel1909** [comment]
> I've added the logo/links text to the branch, feel free to open the PR after you've gone over it @sentinel1909

BTW, yesterday I tested what you've done so far, it works and I was able to get the latest version of cargo-shuttle installed the Windows side of my laptop, where it hadn't been installed before.  Looking at what you've done up to now, I'm realizing you should take the lead here, I'm a bit out of my depth and will take much longer to get anywhere.  I will learn from you!

**Comment by supleed2** [comment]
Ah, alright no worries, I've made some more changes locally and I'll make a PR tomorrow.

@jonaro00 Can we get a redirect similar to the bash one added? Like:

`https://www.shuttle.rs/install-win -> https://raw.githubusercontent.com/shuttle-hq/shuttle/main/install.ps1`

**Comment by jonaro00** [comment]
Yes! You can make the PR for it. Look for the current redirect in the next js config files in the www repo.
