### ISSUE TITLE
[Resources]: Postgres extensions

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1592]
Add commonly used Postgres extensions to the shared cluster and/or the AWS RDS instances.

---
<sub>This issue is a part of the [Product Feature Poll](https://github.com/shuttle-hq/shuttle/issues/1546) ([all issues](https://github.com/shuttle-hq/shuttle/issues?q=label%3A%22Feature+Poll%22+sort%3Acreated-asc)). React with :+1: if you want this feature. Comment if you have suggestions related to this feature.</sub>

**Comment by aniketbiprojit** [comment]
It should probably start with implementing a single extension to establish the convention and then go on adding more. Not sure if this extension is already supported but I would like to see if pg_vector can be supported.

**Comment by joshua-mo-143** [comment]
I think pgcrypto and pg_vector would be two PG extension I'd like to see supported, personally. Not sure what other extensions are popular, but having more options for securing your database data and being able to store vectors is always good.

**Comment by jonaro00** [comment]
Shared Postgres on shuttle.dev now has [common Postgres extensions](https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-extensions.html#postgresql-extensions-16x) due to being based on AWS RDS.

**Comment by carlos-verdes** [comment]
@jonaro00 can we reopen this issue to include a search plugin like `pg_search`?
I could not find any search indexer on that AWS list.

Link to the plugin I found:
https://docs.paradedb.com/deploy/self-hosted/extensions
