### ISSUE TITLE
[Improvement]: Check for installed Cargo in install script

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1603]
### Describe the improvement

The current install scripts, `install.sh` and `install.ps1`, currently start by trying to install a `cargo-shuttle` binary. Only if a binary was not downloaded do they check for if cargo is installed.

The code for checking for the cargo/rust install can be moved to the beginning of the scripts.

It is fine to solve this for just one of the scripts. Up to two people can work on this one :)

---

<sub>This issue is open to contribution. Comment if you want to work on it. Feel free to ask for help and guidance here or in our Discord.</sub>

**Comment by Pulko** [comment]
hey 👋 would like to try working on it

**Comment by jonaro00** [comment]
Solution for Linux is in progress in #1610. Contributing a solution for Powershell is still possible.

**Comment by Pulko** [comment]
@jonaro00 may I still take powershell script? Will create a PR after .sh is done so I would understand how the order should look like

**Comment by jonaro00** [comment]
Yes! Thanks for the heads up.
