### ISSUE TITLE
[Bug]: Error compiling shuttle-common

### ISSUE THREAD

**Issue by sprtd** [shuttle-hq/shuttle#1604]
### What happened?

following the initialization of a project with `cargo shuttle init`, it fails to compile when i try to compile it with the error captured below

### Version

0.37.0

### Which operating system(s) are you seeing the problem on?

macOS

### Which CPU architectures are you seeing the problem on?

ARM64

### Relevant log output

```sh
error[E0706]: functions in traits cannot be declared `async`
  --> /Users/dnn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/shuttle-common-0.37.0/src/backends/client/gateway.rs:38:5
   |
38 |       async fn get_user_projects(
   |       ^----
   |       |
   |  _____`async` because of this
   | |
39 | |         &self,
40 | |         user_token: &str,
41 | |     ) -> Result<Vec<models::project::Response>, Error>;
   | |_______________________________________________________^
   |
   = note: `async` trait functions are not currently supported
   = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
Hey @sprtd! We bumped our minimum supported Rust version a bit early this release, which is what this error indicates. You now need Rust 1.75 to compile this crate, so you'd need to upgrade your local version of Rust for local runs. If you are deploying to an older project that has not been `cargo shuttle restart`ed in a while, you'd also need to do that to ensure the project container is on Rust 1.75.

We're going to be more careful with this in the future, and we're likely going to establish an MSRV policy where we won't upgrade these public crates for a few months after a release. Sorry about the confusion!

**Comment by sprtd** [comment]
Following your suggestion, I upgraded `rustc` to `v1.75.0`, and I'm pleased to confirm that it now compiles successfully. I appreciate your prompt guidance! I would like to kindly close this issue. Many thanks for your assistance!
