### ISSUE TITLE
cargo shuttle ignores Shuttle.toml if run in subdir of crate

### ISSUE THREAD

**Issue by alsuren** [shuttle-hq/shuttle#163]
The logic to find Cargo.toml works fine, but we don't then use the location of Cargo.toml to search for a Shuttle.toml (and will continue as if it's not there). This means that it will have the wrong project name.

I wrote a test for this in https://github.com/shuttle-hq/shuttle/pull/122 to help when implementing this. See https://github.com/shuttle-hq/shuttle/pull/122#discussion_r866546185_

It's very much an edge case, so might not be worth fixing.

**Comment by ivancernja** [comment]
I'll take it!
