### ISSUE TITLE
[Improvement]: Add the `--raw` flag to the `run` and `deploy` commands

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1632]
Currently, the `logs` command has a `--raw` flag that disables the printing of timestamps and origins of log lines:
https://github.com/shuttle-hq/shuttle/blob/c5f2caf037eb5ce05dda80dcd01ba8618319d3be/cargo-shuttle/src/lib.rs#L815-L821

The suggestion is to add this to the local run and deploy commands as well, to that the same behavior is seen when they print their logs.

---

<sub>This issue is open to contribution. Comment if you want to work on it. Feel free to ask for help and guidance here or in our Discord.</sub>

**Comment by nopeNoshishi** [comment]
I would like to try this issue.

**Comment by nopeNoshishi** [comment]
This is a bit of a different discussion, but I think it would be nice to be able to output the log format in json. (Sorry, this is probably not the right place to discuss this.)

**Comment by jonaro00** [comment]
Not a bad idea! The logs request returns the logs in JSON format, so it should be very simple to add that as well. Feel free to try and see what you come up with!

**Comment by nopeNoshishi** [comment]
Hi, I am pleased to inform you that I have opened PR https://github.com/shuttle-hq/shuttle/pull/1653.
