### ISSUE TITLE
[Docs]: Update and improve the Discord weather bot tutorial

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1634]
[This tutorial](https://docs.shuttle.rs/templates/tutorials/discord-weather-forecast) ([source](https://github.com/shuttle-hq/shuttle-docs/blob/main/templates/tutorials/discord-weather-forecast.mdx)) is outdated and we also want a copy of it in shuttle-examples.

We would love if someone could:
- Follow the tutorial to build the bot
- Update it to Serenity 0.12 (and other crates to latest versions)
- Make any other improvements that you think are needed
- Update the tutorial's code snippets and instructions with any changes that were made. The screenshots can remain the same if nothing of substance changed.
- Make a PR to shuttle-examples with the updated code in `serenity/weather-forecast` (a README is not needed since there is a tutorial covering it)
- Make a PR to shuttle-docs with the updated tutorial

---

<sub>This issue is open to contribution. Comment if you want to work on it. Feel free to ask for help and guidance here or in our Discord.</sub>

**Comment by Lonanche** [comment]
I would like to have a go on this

**Comment by Lonanche** [comment]
@jonaro00 

List of changes I made:
-Updated tutorial code snippets to use Serenity 0.12
-Changed one screenshot because discord changed how to obtain discord guild ID
-Submitted final code of tutorial to serenity/weather-forecast in shuttle-examples
-Made some small changes in tutorial because some parts were unclear while I was following it

Let me know if any of the stuff have to be changed!

**Comment by c-git** [comment]
@Lonanche happy you got to this. I was planning to try to do it tonight. So I'll give yours a test run and give you feedback instead.

**Comment by c-git** [comment]
I skimmed through it and it looks good. I didn't actually try it like I planned because I want to use poise for my project as I expect it may grow and that is recommended in the tutorial. Thank you very much for updating this.
