### ISSUE TITLE
[Feature]: Add async-diesel to shuttle-aws-rds

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1692]
### Describe the feature

Add the changes made in #1664 to shuttle-aws-rds

**Comment by sourabpramanik** [comment]
I would like to work on it

**Comment by edgerunnergit** [comment]
As it's been a while I wanted to work on the issue. 

Also I do not have access to an rds instance for testing purposes. Would it be possible to provide a dummy one?
I could also create a draft PR if it helps. 

Here's what I [initially came up with](https://github.com/shuttle-hq/shuttle/commit/f82ceccf8e656bf238913ddcac65192a51a57702)

**Comment by jonaro00** [comment]
@edgerunnergit Running an RDS resource on a local run essentially starts a dummy one for you (a local docker container). If all the feature flags work against local dbs, it should be a sufficient implementation.

**Comment by sourabpramanik** [comment]
@edgerunnergit let me know if you are going to work on this. I was not having enough bandwidth last month to work on this but now I can wrap this week.

**Comment by edgerunnergit** [comment]
@sourabpramanik woul definitely like to work on it. (i have already started experimenting with it)
