### ISSUE TITLE
[Bug]: 405 Method Not Allowed

### ISSUE THREAD

**Issue by mthmcalixto** [shuttle-hq/shuttle#1704]
### What happened?

Why is the /users/create-user route not allowed?

shuttle does not accept Post method?

![image](https://github.com/shuttle-hq/shuttle/assets/121470728/53810237-d601-43d6-a701-7f5cfc17529c)

**My code:** 

```rust
use axum::{
    body::Body,
    http::StatusCode,
    response::{IntoResponse, Response},
    routing::{get, post},
    Json, Router,
};
use serde::Serialize;

#[derive(Serialize)]
struct User {
    id: u64,
    name: String,
    email: String,
}

// Handler for /create-user
async fn create_user() -> impl IntoResponse {
    Response::builder()
        .status(StatusCode::CREATED)
        .body(Body::from("User created successfully"))
        .unwrap()
}

// Handler for /users
async fn list_users() -> Json<Vec<User>> {
    let users = vec![
        User {
            id: 1,
            name: "Elijah".to_string(),
            email: "elijah@example.com".to_string(),
        },
        User {
            id: 2,
            name: "John".to_string(),
            email: "john@doe.com".to_string(),
        },
    ];
    Json(users)
}

async fn router() -> Router {
    // Define Routes
    let app = Router::new()
        .route("/", get(|| async { "Hello, Rust!" }))
        .route("/create-user", post(create_user))
        .route("/users", get(list_users));

    Router::new().nest("/user", app)
}

#[shuttle_runtime::main]
async fn main() -> shuttle_axum::ShuttleAxum {
    let app = router().await;

    Ok(app.into())
}
```

### Version

0.42.0

### Which operating system(s) are you seeing the problem on?

Windows

### Which CPU architectures are you seeing the problem on?

x86_64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
Thanks for the report.
Tried deploying your code and saw the same outcome. Will investigate.

**Comment by mthmcalixto** [comment]
@jonaro00 The problem was https, I used it without https and it gave this error, when using https when starting the URL, it worked. 

without https
![image](https://github.com/shuttle-hq/shuttle/assets/121470728/54d489cb-6f66-44fc-a90a-3cc0538aefe0)

with https
![image](https://github.com/shuttle-hq/shuttle/assets/121470728/d9d07eec-4d1e-41c3-9fa7-cf8d6c80b0c1)

it was just a small detail.
