### ISSUE TITLE
[Improvement]: Bump shuttle-poem to poem 3.0

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1713]
### Describe the improvement

poem 3.0 was released, so shuttle-poem could get a bump, both in this repo and in shuttle-examples.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by sourabpramanik** [comment]
Sorry I didn't asked and create a PR, if it is okay can you assign me this
