### ISSUE TITLE
feature: cargo shuttle init

### ISSUE THREAD

**Issue by christoshadjiaslanis** [shuttle-hq/shuttle#175]
Introduce an `init` function to `cargo-shuttle` that will initialise the barebones of a project (similar to `cargo init`). `cargo shuttle init <name>`

This should probably:
1. Add an `Init(ProjectName)` variant to `Command` in `args.rs` 
2. Call `cargo init --lib` via the `cargo` crate
3. Automatically add the `crate-type = ["cdylib"] ` to `cargo.toml`
4. Add the `shuttle-service` deps top `cargo.toml`.

Bonus points - have a separate `cargo init` command for each framework supported. For example with Rocket:
1. `cargo shuttle init-rocket <name>`
2.  As above, but also add the feature flags: `shuttle-service = { version = "0.2", features = ["web-rocket"] }`
3.  Also create `hello-world` scaffolding
```rust
#[macro_use]
extern crate rocket;

use rocket::{Build, Rocket};

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[shuttle_service::main]
async fn rocket() -> Result<Rocket<Build>, shuttle_service::Error> {
    Ok(rocket::build().mount("/hello", routes![index]))
}
```

**Comment by nahuakang** [comment]
I'd be happy to claim this if no one else is working on it yet and it's not high priority time-wise on shuttle's roadmap :)

**Comment by brokad** [comment]
> I'd be happy to claim this if no one else is working on it yet and it's not high priority time-wise on shuttle's roadmap :)

Thanks @nahuakang!

> Edit: After asking around and doing some investigation, it seems that cargo init [writes naively to files](https://github.com/rust-lang/cargo/blob/39ad1039d9e3e1746177bf5d134af4c164f95528/src/cargo/ops/cargo_new.rs#L766-L793) and we could use [toml-edit](https://crates.io/crates/toml-edit) for modifying an existing Cargo.toml file.

Sounds like a plan!
