### ISSUE TITLE
[Bug]: If you paste an API key copied with `cargo shuttle init --create-env`, you will get `Invalid API key`.

### ISSUE THREAD

**Issue by dijdzv** [shuttle-hq/shuttle#1764]
### What happened?

I ran `cargo shuttle init --create-env` and when it asked for the API Key, I copied it from the shuttle console page and pasted it into the vscode terminal (powershell). Then I got an `Invalid API key` error.

The process proceeded normally when the API key was entered manually.

### Version

v0.44.0

### Which operating system(s) are you seeing the problem on?

Windows

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
✘ Invalid API key:
The API key should consist of only alphanumeric characters.       
The API key should be exactly 16 characters in length.
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
@dijdzv
- When pasting text in the terminal, did you use Ctrl+Shift+V?
- You can also log in with `cargo shuttle login --api-key <key>`. That way you can verify that the text has been pasted correctly.

**Comment by dijdzv** [comment]
@jonaro00 

Oh, I went home and tried again and the process went through with no problem. It seems the computer was either in a bad or unexpected state.

Thanks for taking care of it.
