### ISSUE TITLE
[Bug]: 502 Bad Gateway

### ISSUE THREAD

**Issue by TannerJ07** [shuttle-hq/shuttle#1769]
### What happened?

i did project status and it errored. I dont know what it is supposed to do.

### Version

v0.44.0

### Which operating system(s) are you seeing the problem on?

Windows

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
C:\Users\%USER%\projects\rusty-calculator>cargo shuttle project status

Getting project status failed

If getting project status failed repeatedly, please check Shuttle status at https://status.shuttle.rs before contacting the team on the Discord server.
Error: 502 Bad Gateway
Message: Did not understand the response from the server. Please log a ticket for this
```

### Duplicate declaration

- [x] I have searched the issues and there are none like this.

**Comment by TannerJ07** [comment]
calling cargo shuttle deploy worked

**Comment by jonaro00** [comment]
@TannerJ07 Thanks for reporting.
Does this happen every time you do the command? It could have been a rare (and unlucky) error.

**Comment by TannerJ07** [comment]
It happened repeatedly. I also tried closing command prompt and reopening it, but the deploy command worked.

**Comment by TannerJ07** [comment]
It doesn't seem to be happening anymore

**Comment by iulianbarbu** [comment]
> It doesn't seem to be happening anymore

Thanks for letting us know! Don't hesitate to reopen this issue if it happens again.
