### ISSUE TITLE
feature: test / staging environments

### ISSUE THREAD

**Issue by christos-h** [shuttle-hq/shuttle#177]
Shuttle only has a production environment right now. Obviously as your developing features you may want to deploy to a temporary testing environment to try out your changes before pushing to production.

This is quite a big one - requires quite a bit of design and changes to infrastructure.

**Comment by jonaro00** [comment]
Seems like this is already possible to some degree.
If your project is called `abc`, you could simply do a (dirty) deploy to a parallel project container `abc-staging-n3if7shj3`.
But it can of course be built into Shuttle with more streamlined support in the "main" project.

**Comment by jonaro00** [comment]
Closing in favour of #1548
