### ISSUE TITLE
I am really confused about the pricing and where the app is hosted.

### ISSUE THREAD

**Issue by NikosEfthias** [shuttle-hq/shuttle#178]
The website including the blog does not contain any information about the business side of the things.
Where can one see the pricing and limits info ?

**Comment by christoshadjiaslanis** [comment]
Hey! Shuttle's completely free while it's in Alpha and we're figuring out the kinks in the platform. There are no imposed limits on the platform right now - but you may hit the limits of the underlying hardware if you have a large workload. I'll be updating the website and README soon to have more detailed information on all this stuff.

Hope this helps!

**Comment by NikosEfthias** [comment]
thanks that little bit clarifies things.
