### ISSUE TITLE
[Bug]: lost access to projects / project booting up forever / Project restart failed / Error 500

### ISSUE THREAD

**Issue by cadunass** [shuttle-hq/shuttle#1807]
### What happened?

I am experiencing a very troubling issue where my projects just dont work anymore, they are all stuck in this "This project is booting up, please refresh the page in a few seconds" status. I can see the projects in shuttle console but they all show this same message when opening them, and if trying to send any request to one of them I get a 600 error "Project is not ready. Try to restart it" and "Project is running but is not responding correctly. Try to restart it".

I started using shuttle a few months ago with a single deployed project running. It was ok and I dindt experience any issues. After some time (few months) I created another project and first experienced this issue after a few days. I got stuck with these errors, couldnt restart and even delete the project, so I created a new project in shuttle and the same thing happened after a few days again. Now I cant access any of my projects and also I can no longer access the resources from them.

- Restarting the project with "cargo shuttle project restart" and got this output:
```
using "cargo shuttle project restart" and got this output after a while:
Project "MYPROJECTNAME" is destroyed
Run `cargo shuttle project start` to recreate project environment on Shuttle.

Project creation failed

Please double-check the project status before retrying:

cargo shuttle project status

If the project creation or retrieving the status fails repeatedly, please check Shuttle status at https://status.shuttle.rs before contacting the team on the Discord server.

Project restart failed

Please double-check the project status before retrying:

cargo shuttle project status

If restarting your project or checking its status fail repeatedly, please check Shuttle status at https://status.shuttle.rs before contacting the team on the Discord server.
Error: 500 Internal Server Error
Message: Our server was unable to handle your request. A ticket should be created for us to fix this.
```

- Running "cargo shuttle project status -f" and got this output:
```
Error: 500 Internal Server Error
Message: Our server was unable to handle your request. A ticket should be created for us to fix this.
```

- Deleting the project with "cargo shuttle project delete" and got this output:
```
Project delete failed

Please double-check the project status before retrying:

cargo shuttle project status

If deleting the project or getting project status fails repeatedly, please check Shuttle status at https://status.shuttle.rs before contacting the team on the Discord server.
Error: failed to make delete request

Caused by:
    0: error sending request for url (https://api.shuttle.rs/projects/MYPROJECTNAME/delete): operation timed out
    1: operation timed out
```

### Version

v0.46.0

### Which operating system(s) are you seeing the problem on?

Linux, In deployment

### Which CPU architectures are you seeing the problem on?

x86_64, In deployment

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
Hi,
There was some platform degradation at the time you wrote this issue.
Could you try again and let us know if you still get the same errors?
