### ISSUE TITLE
[Feature]: `cargo shuttle upgrade`

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#1840]
### Describe the feature

Add a command that runs either
`curl -sSfL https://www.shuttle.rs/install | bash` with bash
or
`iwr https://www.shuttle.rs/install-win | iex` with powershell
based on which platform cargo-shuttle was compiled on

### Suggestion or Example of how the feature would be used

Just a convenience over having to look up the installer command every time.
In the future, this command could also help with bumping dependencies, etc.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by supleed2** [comment]
I'd like to take a shot at this one :)
