### ISSUE TITLE
[Improvement]: bump sqlx to 0.8.2

### ISSUE THREAD

**Issue by nicolasauler** [shuttle-hq/shuttle#1863]
### Describe the improvement

This will allow consumers of the crate to update to the latest sqlx.
Also, sqlx <= 0.8.0 has a reported security vulnerability, and the fix is at 0.8.1.

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by nicolasauler** [comment]
I'm also onboard for helping solve this issue, as I'm an interested party.
I just never opened a PR on this repo and maybe could use some guidance, although from what I've seen the Contribution and Developing guides are quite thorough.

**Comment by jonaro00** [comment]
Thanks for giving attention to this. It's an easy change to make: Bump the version in the shared db and AWS RDS crates, and make sure they compile. After that works, all examples using it can be updated.

**Comment by jonaro00** [comment]
I forgot that we already did this in https://github.com/shuttle-hq/shuttle/pull/1847. What we can do now that 0.8.1 is released is to bump it again. There is a bug in 0.8.1 that will make it not compile on Rust < 1.80 which our CI uses, but we can ignore that (just run the CI command locally with 1.80).

**Comment by GnomedDev** [comment]
Seems like sqlx dep has already been bumped, and all that is needed is a new breaking release of `shuttle-shared-db`.

**Comment by jonaro00** [comment]
Yep, solved in #1867. Awaiting release.

**Comment by joshua-mo-143** [comment]
SQLx has been bumped to 0.8.2 on `shuttle-shared-db` 0.48.0! You should now be unblocked from this.

**Comment by nicolasauler** [comment]
Thanks a lot, my friends!
Closing issue as resolved.
