### ISSUE TITLE
[Improvement]: rust stable version in runner

### ISSUE THREAD

**Issue by nicolasauler** [shuttle-hq/shuttle#1882]
### Describe the improvement

I couldn't find out if the runner rust version will become 1.81 stable in the next shuttle release (0.48).
If not, can we upgrade it?

I'm getting this error because some of my dependencies are crazy I guess and have MSRV as 1.81 haha

![image](https://github.com/user-attachments/assets/c6dd3c93-835f-4f04-ae43-67fa6adc032e)

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by oddgrd** [comment]
No problem, we can upgrade it :+1:

**Comment by jonaro00** [comment]
#1883
