### ISSUE TITLE
feature: support path dependencies

### ISSUE THREAD

**Issue by christos-h** [shuttle-hq/shuttle#190]
`cargo-shuttle` uses `cargo package` under the hood to package project files into a tarball and ship them to the shuttle api for them to be built.

A limitation of `cargo package` is that it will refuse to package path dependencies.

Implementation of this is unclear - some design is required as with the current build system changes to the underlying file-system will probably be required.

**Comment by gzeronet** [comment]
When deploying (rapp is a custom local crate, I just follow sea-orm docs:https://www.sea-ql.org/SeaORM/docs/migration/setting-up-migration/#app-crate ) , it shows:
```
Caused by:
    all dependencies must have a version specified when packaging.
    dependency `rapp` does not specify a version
    Note: The packaged dependency will use the version from crates.io,
    the `path` specification will be removed from the dependency declaration.
```
Hope the feature works and remove version check, thx.

**Comment by oddgrd** [comment]
Closed in https://github.com/shuttle-hq/shuttle/pull/501
