### ISSUE TITLE
feature: tailing logs

### ISSUE THREAD

**Issue by christoshadjiaslanis** [shuttle-hq/shuttle#193]
`cargo-shuttle` has logging functionality with `cargo shuttle logs` - but this prints the entire log history of a deployment and terminates.

This feature proposes log tailing, where the user can have access to a constant stream (follow basically) of logs from `cargo-shuttle` using `cargo shuttle logs --tail` or `cargo shuttle logs -t`.

**Comment by jmwill86** [comment]
I'd be happy to take this one. Is it just a live update of the last X lines of the log @christoshadjiaslanis ?

**Comment by chesedo** [comment]
Sorry for only seeing this now @jmwill86. This is more of following / streaming the logs as new logs come in.

Are you still up for taking this?

**Comment by jmwill86** [comment]
Yeah happy to give it a go. My local setup's been broken and haven't had a lot of time but I'll get working on it asap. 👍

**Comment by chesedo** [comment]
The v0.6.0 added the `--follow` flag
