### ISSUE TITLE
feature: Support actix web as a web framework

### ISSUE THREAD

**Issue by kaleidawave** [shuttle-hq/shuttle#205]
Some mentions of [actix web](https://actix.rs/) [in this thread](https://www.reddit.com/r/rust/comments/v6rfqr/hyper_vs_rocket_low_level_vs_batteries_included/). Would be great to get support at some point!

(should be somewhat simple to implement `Service` for [actix_web::HttpServer](https://docs.rs/actix-web/4.0.1/actix_web/struct.HttpServer.html) )

**Comment by oddgrd** [comment]
Hi! I'd like to work on this one. I will probably need some guidance, but I'll get started and see how I progress first.

**Comment by oddgrd** [comment]
Closed in #491 :partying_face:
