### ISSUE TITLE
bug: `cargo-shuttle`fails to parse a dependency without a patch version

### ISSUE THREAD

**Issue by chesedo** [shuttle-hq/shuttle#213]
Our version checker in `cargo-shuttle` fails to parse a `shuttle-service` version when it is missing a patch like the following definition:

```toml
shuttle-service = { version = "0.2", features = ["sqlx-postgres", "web-rocket"] }
```

**Comment by chesedo** [comment]
The quick fix for now is to specify a full version like

```toml
shuttle-service = { version = "0.2.2", features = ["sqlx-postgres", "web-rocket"] }
```

**Comment by jmwill86** [comment]
Is there anything I need to do with this to close it @chesedo? I dont think there's anything more to be done.

**Comment by chesedo** [comment]
@jmwill86 I also don't see anything more to do. Just missed that this can be closed :smile:
