### ISSUE TITLE
sqlx version mismatch error

### ISSUE THREAD

**Issue by Xavientois** [shuttle-hq/shuttle#240]
When I try to call `cargo shuttle run` with the example postgres code from the [docs](https://docs.rs/shuttle-service/latest/shuttle_service/#using-sqlx), I get the following error:

```
error[E0308]: mismatched types
  --> src/lib.rs:16:17
   |
16 | async fn rocket(pool: PgPool) -> ShuttleRocket {
   |                 ^^^^ expected struct `Pool`, found struct `sqlx_core::pool::Pool`
   |
   = note: expected struct `Pool<Postgres>`
              found struct `sqlx_core::pool::Pool<sqlx_core::postgres::database::Postgres>`
   = note: perhaps two different versions of crate `sqlx_core` are being used?
```

My dependencies are:
```
shuttle-service = { version = "0.3.3", features = ["web-rocket", "sqlx-postgres"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres"] }
```

Changing the `sqlx` version to `0.5` fixes the error, but I wonder what the best approach for avoiding this kind of version mismatch would be.

**Comment by oddgrd** [comment]
This hasn't been resolved, but I'm closing this in favor of #505 which is more descriptive. Thanks!
