### ISSUE TITLE
Compose.dev.yml uses sometimes-deprecated `extends` feature

### ISSUE THREAD

**Issue by SonicZentropy** [shuttle-hq/shuttle#241]
Shuttle's dev.yml attempts to `extend` the base `backend`, but the backend `depends_on` the `provisioner` service.  It seems some versions of Compose no longer allow to `extends` a service that contains a `depends_on`, particularly ones post-3 but prior to the current version.

See the note in Compose's docs: https://docs.docker.com/compose/extends/#extending-services

The version of Compose the install guide led me to was one of these.  I was eventually able to solve it by manually installing a fresh Compose binary as a CLI Plugin, but it took a while to figure out the issue.  I'd imagine I won't be the last person to encounter this.  Would everyone be open to adding a note to the Contributing/setup instructions mentioning it?

**Comment by chesedo** [comment]
Thanks for the headsup @SonicZentropy. This should be closed by #244
