### ISSUE TITLE
Allow examples to run locally

### ISSUE THREAD

**Issue by Xavientois** [shuttle-hq/shuttle#250]
When trying to run the Rocket Postgres and URL Shortener examples locally, they fail due to a compilation error:
```
error[E0433]: failed to resolve: use of undeclared crate or module `shared`
  --> src/lib.rs:52:19
   |
52 | async fn rocket(#[shared::Postgres] pool: PgPool) -> shuttle_service::ShuttleRocket {
   |                   ^^^^^^ use of undeclared crate or module `shared`
```

I tried to fix it with this PR https://github.com/shuttle-hq/shuttle/pull/249, but when the CI ran, it gave me the following error [here](https://app.circleci.com/pipelines/github/shuttle-hq/shuttle/40/workflows/52a963a8-2783-42fa-b49e-3511b23d4684/jobs/41?invite=true#step-114-349):
```
error: resource needs an attribute configuration
  
 = help: Try adding a config like `#[shared::Postgres]`
  
 --> src/lib.rs:52:17
   |
52 | async fn rocket(pool: PgPool) -> shuttle_service::ShuttleRocket {
   |                 ^^^^
```

I have struggled to find documentation on this error and this annotation, so it has been difficult to try to make a fix for  this.

**Comment by chesedo** [comment]
This annotation is for the new release which was finally released this morning :tada:

You should no longer getting this error after updating using:
```bash
cargo install cargo-shuttle
```

Would you mind confirming if the update fixes it?

**Comment by Xavientois** [comment]
Just tested and it looks like it's working great now!

It might make sense to link to the example code for the latest released version of `cargo-shuttle` rather than `main`, to avoid similar confusion for first-time users in the future.
