### ISSUE TITLE
Link to released example code in website

### ISSUE THREAD

**Issue by Xavientois** [shuttle-hq/shuttle#255]
On the website, instead of linking to the example code on `main`:

> It might make sense to link to the example code for the latest released version of `cargo-shuttle` rather than `main`, to avoid similar confusion for first-time users in the future.

_Originally posted by @Xavientois in https://github.com/shuttle-hq/shuttle/issues/250#issuecomment-1180549336_

**Comment by chesedo** [comment]
It would be great if the solution also updates our [release script](https://github.com/shuttle-hq/shuttle/blob/main/scripts/release.sh). That way there is no need to manually search and update all our doc entries.

**Comment by oddgrd** [comment]
We currently don't update the main branch of the examples until we start the next release, so I'll close this. Thanks!
