### ISSUE TITLE
E2E tests fail due to container being marked for removal

### ISSUE THREAD

**Issue by Xavientois** [shuttle-hq/shuttle#260]
For some of my PRs the CI will run successfully until the E2E test step, where it will fail with the following error:

```
Error response from daemon: container is marked for removal and cannot be started
make: *** [Makefile:46: up] Error 1
CONTAINER_REGISTRY=public.ecr.aws/q0k3o0d8 docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
```

[example](https://app.circleci.com/pipelines/github/shuttle-hq/shuttle/62/workflows/46483f8a-ae6c-46e4-bfd5-ab2d7f046a13/jobs/64?invite=true#step-114-198)

I do not know what causes this error, but it makes opening PRs a bit more difficult of a process.

**Comment by chesedo** [comment]
I know this specific error no longer happens on CI. Closing for now.
