### ISSUE TITLE
Support `cargo shuttle init --actix-web`

### ISSUE THREAD

**Issue by nahuakang** [shuttle-hq/shuttle#263]
The `cargo shuttle init` command will support the following flags after #238 is merged:

- `--axum`
- `--rocket`
- `--tide`
- `--tower`

Todo's:

- Per #205, we could add an `--actix-web` flag to `cargo shuttle init`.
- Per #269, we could add an `--poem` flag to `cargo shuttle init`.

Since I worked on `cargo shuttle init`, I'd be happy to patch these 2 flags.

**Comment by oddgrd** [comment]
Closed in #275 and #491, thanks again for `init` Nahua!
