### ISSUE TITLE
Support feature web-poem

### ISSUE THREAD

**Issue by gzeronet** [shuttle-hq/shuttle#269]
Just tried add feature web-poem, seems too hard to me in rust.
Hope that can work, thx.
https://github.com/poem-web/poem

BTW, awesome platform, that's what I want.

**Comment by oddgrd** [comment]
I'd like to work on this. It's similar to the actix integration I'm working on already, but it looks like it will be a bit simpler to implement.

**Comment by sunli829** [comment]
> I'd like to implement this. It's similar to the actix integration I'm working on already.

Thank you! 🙂

**Comment by oddgrd** [comment]
No problem. 🙂 Thank you for poem and async-graphql!

**Comment by gzeronet** [comment]
@oddgrd Thx for all you did. Waiting for the next release.

**Comment by gzeronet** [comment]
It works!!!
