### ISSUE TITLE
cargo shuttle init --rocket --hello-world

### ISSUE THREAD

**Issue by Butch78** [shuttle-hq/shuttle#313]
When using the init rocket example you'll get the following error:

![image](https://user-images.githubusercontent.com/19205392/185934229-0959dc0c-3f5e-4a56-9b77-d8b8b369ea11.png)

This is due to the wrong dependencies for Rocket being added to the cargo.toml as shown belown:
![image](https://user-images.githubusercontent.com/19205392/185934369-0f9690e9-192c-4f5b-9fc1-1c2c79b82ebe.png)

It should instead be ```0.5.0-rc.2"```

**Comment by Butch78** [comment]
I tried to modify  the GetDependencyVersionFn but I was unable to get it to return the pre_release and when I tried to change the boilerplate code for the rocket to a 0.4.2 version Shuttle was not happy with the lack of main function.

**Comment by chesedo** [comment]
The fix should be to make [this hard coded false on `get_latest_dependency()`](https://github.com/shuttle-hq/shuttle/blob/3210c6a4e01e11dfcb4e6169e79db3a02390d039/cargo-shuttle/src/init.rs#L428) a function argument and making the argument [true for rocket](https://github.com/shuttle-hq/shuttle/blob/3210c6a4e01e11dfcb4e6169e79db3a02390d039/cargo-shuttle/src/init.rs#L85) somehow :sweat_smile: .

A simple test should be just setting the hard coded `false` to `true`

**Comment by chesedo** [comment]
Fyi, [here the GetDependencyVersionFn pointer is set to get_latest_dependency_version](https://github.com/shuttle-hq/shuttle/blob/3210c6a4e01e11dfcb4e6169e79db3a02390d039/cargo-shuttle/src/init.rs#L367) (which is where the hard coded false of the previous comment appears) :smile:

**Comment by nahuakang** [comment]
Even more context, we're using: http://killercup.github.io/cargo-edit/cargo_edit/fn.get_latest_dependency.html. @chesedo Should I make a fix here (since I wrote the code)?

**Comment by chesedo** [comment]
@nahuakang any brave soul can take this :grin: So whoever has the time and claims this one first can have it

**Comment by coszio** [comment]
I'll take this one! 🔥
