### ISSUE TITLE
regression when moving from cargo-shuttle 0.4.0 to 0.5.1 -> Error 502 bad gateway

### ISSUE THREAD

**Issue by s-d-m** [shuttle-hq/shuttle#328]
Hi,

I tried to update the cargo-shuttle dependency version from 0.4.0 to 0.5.1 and `cargo shuttle deploy` fails with `error 502 bad gateway`.
I did reinstall cargo-shuttle before trying to redeploy, and also cleaned and recompile too. Running `cargo shuttle run` works.

The project I tried to deploy is available at https://github.com/s-d-m/lilyplayer-web

**Comment by ho-229** [comment]
I encountered the same problem

**Comment by CarreraPHP** [comment]
i am using shuttle for the first time & the version is `cargo-shuttle 0.12.0`. I also faced the `502 bad gateway` error for the first time. on the next run, everything worked.

Information about this error, should be available in the FAQ page.
