### ISSUE TITLE
`shutte init` : add `publish: false` in cargo.toml

### ISSUE THREAD

**Issue by tguichaoua** [shuttle-hq/shuttle#352]
I suggest adding `publish: false` in the `cargo shuttle init` generated cargo.toml to avoid accidental `cargo deploy`.

**Comment by christoshadjiaslanis** [comment]
> I suggest adding `publish: false` in the `cargo shuttle init` generated cargo.toml to avoid accidental `cargo deploy`.

Do you mean to avoid accidental `cargo publish`?

**Comment by tguichaoua** [comment]
> > I suggest adding `publish: false` in the `cargo shuttle init` generated cargo.toml to avoid accidental `cargo deploy`.
> 
> Do you mean to avoid accidental `cargo publish`?

Yes, my bad.
