### ISSUE TITLE
Error deploying workspace with library crate.

### ISSUE THREAD

**Issue by casperstorm** [shuttle-hq/shuttle#417]
I've created a very simple Discord bot with serenity to test Shuttle: https://github.com/casperstorm/discord-bot-einar/tree/workspace-lib-crates.
Running `cargo shuttle run` works just fine:

```
Starting discord-bot-einar on http://127.0.0.1:8000
2022-10-20T15:01:15.904846000Z  INFO serenity::client::bridge::gateway::shard_manager: Telling shard queuer to start shard 0
2022-10-20T15:01:16.149037000Z  INFO serenity::client::bridge::gateway::shard_runner: [ShardRunner [0, 1]] Running
2022-10-20T15:01:16.406885000Z  INFO discord_bot_einar: BOT Einar is connected
```

However when running `cargo shuttle deploy` i get the following error:

> {error="Build error: failed to select a version for the requirement `data = \"^0.1.0\"`\ncandidate versions found which didn't match: 0.0.0\nlocation searched: crates.io index\nrequired by package `discord-bot-einar-c1fabb48-fb8c-4b83-9977-ad647b5ecea9 v0.1.0 (/opt/shuttle/shuttle-builds/discord-bot-einar)`"}

Do i have to do something different with my current structure of the bot? The structure is as follows:

```
├── Cargo.lock
├── Cargo.toml
├── data
│   ├── Cargo.toml
│   └── src
│       ├── data_time.rs
│       ├── lib.rs
│       └── rss.rs
└── src
      ├── lib.rs
      ├── rss.rs
      └── settings.rs
```

**Comment by casperstorm** [comment]
I got a answer from [Shuttle Discord](https://discord.gg/HBan6PGG).

> Currently we use cargo package (https://doc.rust-lang.org/cargo/commands/cargo-package.html) to package users crates before sending them to the build server. This means that all crates used must be indexed on crates.io, so depending on an unpublished crate from a workspace won't work (neither will git dependencies).
This is something we want to support, but haven't been able to solve yet.

**Comment by chesedo** [comment]
This should work after #767
