### ISSUE TITLE
Support for Yew

### ISSUE THREAD

**Issue by bcpeinhardt** [shuttle-hq/shuttle#452]
I wanted to try deploying a yew app with shuttle. I set up what I thought would be the natural minimum setup to deploy the yew app on top of an axum backend, but when I deploy it doesn't show up :/ Would someone be able to help me get the basic example working, and then I can add it to the examples for the repo?

https://github.com/bcpeinhardt/yewaxumshuttle

**Comment by oddgrd** [comment]
Hello again Benjamin! While it is planned, serving static assets isn't supported yet. For reference, here is a thread about this on our discord: https://discord.com/channels/803236282088161321/1020834755035545600. Lately we've been focusing on improving stability and security, but as we get back to adding features this will be high on the list.

**Comment by bcpeinhardt** [comment]
Thank you!

**Comment by robertohuertasm** [comment]
@bcpeinhardt probably you already saw it but just in case: [Axum static files example](https://github.com/shuttle-hq/examples/tree/main/axum/static-files).

**Comment by bcpeinhardt** [comment]
I didn't but this is awesome, thank you!!!!

**Comment by robertohuertasm** [comment]
you're welcome! I guess you could close the issue.

**Comment by bcpeinhardt** [comment]
Haha I guess I could!
