### ISSUE TITLE
feature: Pre-built binaries with releases

### ISSUE THREAD

**Issue by tsar-boomba** [shuttle-hq/shuttle#489]
Using Shuttle in ci is currently a pain. It takes about 8 mins to build from source on gh actions runners. I would like to propose pre-built binaries for windows, macOS (x86 + aarch64), and Linux. I could set up an action that runs when a new tag is pushed to the main branch. The main hurdle with this is that the action would also have to produce the release so it can attach the binaries to it. I'd be willing to contribute this, feedback is appreciated.

**Comment by oddgrd** [comment]
Indeed, I feel your pain! We actually have a PR for this now: https://github.com/shuttle-hq/shuttle/pull/483, so pre-built binaries should be available for the next release.

Either way, thank you for offering to do this. If there's anything else you feel is missing, or would like to contribute, feel free to reach out!

**Comment by tsar-boomba** [comment]
Didn't see that, that's great, I'll close this in favor of that.
