### ISSUE TITLE
`project new` subcommand waits for environment to be ready

### ISSUE THREAD

**Issue by brokad** [shuttle-hq/shuttle#492]
Currently, running `cargo shuttle project new` returns immediately with a prompt stating the project is `creating`. 

However, the environment is not ready to be deployed to until `cargo shuttle project status` returns `ready`. Most times this is not a big deal, but under high load, environment creation can take a minute or so, which can be unexpectedly long and create a bad experience as users don't know when their environment is finally ready.

Maybe it'd be better to hold exiting from `project new` until the project is ready, continuously updating the prompt with the latest state, and including a spinner to show there is work in progress. This also requires covering the [entire state machine of environments](https://github.com/shuttle-hq/shuttle/blob/e3fb067b3e62b399b800f591df5404797f7581ce/gateway/src/project.rs#L147).

If users exit early from the prompt, they should be able to go back into the "blocking, continuously updating state" through `project status --wait`, which should be equivalent.

**Comment by chesedo** [comment]
Thanks for this @brokad. The prefered solution for this should use websockets rather than a polling model (if possible).

I'm wondering if `project status --follow` won't be more idiomatic?

**Comment by brokad** [comment]
> I'm wondering if project status --follow won't be more idiomatic?

Sure, I'm fine either way.

**Comment by guerinoni** [comment]
I will try to implement it :)
