### ISSUE TITLE
Fail to deploy due to incompatible version of rustc

### ISSUE THREAD

**Issue by snylonue** [shuttle-hq/shuttle#527]
log: `cargo shuttle logs 4857c73c-aef9-4d44-a19a-2895ceca2b3d `
environment: both Ubuntu in wsl2 and github actions
project: https://github.com/snylonue/annil-serverless

It works well if I run `cargo shuttle run`, but when running `cargo shuttle deploy`, it complains `found crate * compiled by an incompatible version of rustc.`, even if I switched to the required rustc(`rustc 1.59.0 (9d1b2106e 2022-02-23)`).

What confuses me is that shuttle reports the rustc used is `1.63.0` while I have rustc `1.65.0` installed.

```
rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/sudo_snylonue/.rustup

installed toolchains
--------------------
stable-x86_64-unknown-linux-gnu (default)
1.59.0-x86_64-unknown-linux-gnu 

active toolchain 
---------------- 
stable-x86_64-unknown-linux-gnu (default)
rustc 1.65.0 (897e37553 2022-11-02) 
```

**Comment by oddgrd** [comment]
Yeah, we've seen this before with `dashmap` and `hashbrown`. I have tried to override this behavior myself, but I haven't been able to yet. I have a few ideas I'm going to explore next week, I'll report back when I know more.

**Comment by snylonue** [comment]
I have successfully deployed by manually patching the crates with rust-toolchain.toml, which can serve as a temporary fix.

**Comment by oddgrd** [comment]
Ah of course, that's possible now. Good thinking @snylonue, thanks!

**Comment by snylonue** [comment]
When will the fix be deployed?
