### ISSUE TITLE
Add a PoiseService for serenity

### ISSUE THREAD

**Issue by techs-sus** [shuttle-hq/shuttle#552]
Poise is a framework for serenity, and it is quite easy to implement. I think that we should implement service for the struct, and not the direct framework object.

**Comment by chesedo** [comment]
Trying to implement Poise as a [custom shuttle service](https://docs.shuttle.rs/examples/custom-service) will be a good place to start. Once this works it's quite easy to make it part of the code base since it mostly involves removing the wrapper that is created for the custom service.

**Comment by Anafabula** [comment]
@chesedo I made Poise into a custom shuttle service [here](https://github.com/Anafabula/mc-status-bot/blob/master/src/lib.rs#L25). It runs fine with `cargo shuttle run`, but doesn't deploy because of #527.

**Comment by chesedo** [comment]
Nice, okay, I know some work is happening internally regarding #527 so will hopefully have an update here soon

**Comment by chesedo** [comment]
@Anafabula our fix for #527 has been merged :partying_face: . It will be great if you can make a PR with your service impl in [shuttle-service](https://github.com/shuttle-hq/shuttle/blob/main/service/src/lib.rs#L651-L659)
