### ISSUE TITLE
Other DB names not from my project visible in pgAdmin

### ISSUE THREAD

**Issue by ephraimkunz** [shuttle-hq/shuttle#557]
1. Create a project that uses `shuttle_shared_db::Postgres` and deploy it.
2. You get back a string like this after deployment: `postgres://user-punchcards-server:<redacted>@db.shuttle.rs:5432/db-punchcards-server`. 
3. Use that string which includes a username, password, hostname, and db name to connect to the server in pgAdmin.
4. View the databases drop-down. It lists all databases under that host name, including those from other users. I should not be able to view the names of the databases from other users sharing the same DB server.

**Comment by oddgrd** [comment]
We have tried to limit this as much as we can, but it is indeed still not good enough. We'll try to tweak it further to avoid any information leaking (to be clear though, other users will not be able to access your DB). 

In the meantime, the RDS databases are not shared and offer complete isolation: https://docs.shuttle.rs/resources/shuttle-aws-rds
