### ISSUE TITLE
Add resource to get Shuttle service info

### ISSUE THREAD

**Issue by sd2k** [shuttle-hq/shuttle#562]
It's not ideal, but there may be some cases where the app will need to know some information about the environment it's running on, most notably the public URL. I'm currently using a [custom resource](https://github.com/sd2k/recipes/blob/eeb0e512906742baf215dffb5a31587de90b8f74/crates/recipe-shuttle/src/service_info.rs) to get the service name and creating a URL out of that, but it might be nice to provide a first-class Resource for the same thing. Happy to send a (more generalized) PR if you think it'd be useful!

**Comment by oddgrd** [comment]
Hey @sd2k, apologies for the delayed reply. Is this something you're still interested in working on? We've had another request for this now, and your proposed solution seems interesting!

**Comment by sd2k** [comment]
Hey @oddgrd, yeah I can fire off a PR. I originally wrote it against Shuttle 0.8.0 or something and there's been some big changes to custom resources since then so I'm not 100% confident in it, but that's what reviews are for, right? 😂

**Comment by oddgrd** [comment]
Great, happy to hear that! 🥳 Yeah, it's changed quite a bit since then, so feel free to open a PR or a draft PR with any questions you may have. It may be useful to look at PRs for other resources that have been added more recently, like the Turso resource.
