### ISSUE TITLE
Add workspace support

### ISSUE THREAD

**Issue by chesedo** [shuttle-hq/shuttle#564]
When I deploy a crate that is within a workspace and that has a `{ workspace = true }` dependency, then I get an error that the manifest cannot be parsed.

The reason for this is because shuttle did not archive the entire workspace, but only the single crate.

**Comment by gautamprikshit1** [comment]
Any help on how to achieve this

**Comment by chesedo** [comment]
I can think of the following changes that will be needed (each in a separate PR):
1. Our way of finding the `Cargo.toml` file is wrong since it currently stops at the first one found. Rather it should do whatever `cargo` is doing to continue looking in the parent tree for another `Cargo.toml` that might be the workspace one. When shuttle collects the correct `Cargo.toml` (for the workspace) then I believe everything is already in place for shuttle to correctly archive the entire workspace. Identifying the correct `Cargo.toml` is a change that needs to happen in `cargo-shuttle` somewhere.
2. We have a `loader.rs` file (in service) which builds an archive, but then only gets the first `cdylib` from the build. Since the archive is now the entire workspace there might be multiple `cdylib`s so this build method needs to be updated to return a `Vec<_>`. The caller might then also need a small update, but I believe shuttle has everything else in place to support running multiple services / crates in a workspace.

**Comment by brokad** [comment]
Just to confirm here @chesedo, I suppose this also requires a change in deployer somewhere since a workspace could contain multiple services, each of which needs recognition in the deployer's state?

**Comment by chesedo** [comment]
@brokad the deployer state can already start multiple services. For services that depend on one another, starting them in the correct order is just missing.

**Comment by chesedo** [comment]
Change number 2 for the above comment is implemented in #767
