### ISSUE TITLE
Add -r / --release flag to `cargo-shuttle run`

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#609]
Add an argument to `cargo-shuttle` that sets the flag at
https://github.com/shuttle-hq/shuttle/blob/main/cargo-shuttle/src/lib.rs#L393
to `true` to allow local runs to use release build.

Since `cargo-shuttle run` is basically a wrapper around `cargo run`, there could also be other flags that are of interest to implement. But since the release mode flag is already supported by the loader, it should be an easy addition.

**Comment by oddgrd** [comment]
Good idea, and it should indeed be straightforward to implement. Thanks!
