### ISSUE TITLE
Shuttle.toml documentation

### ISSUE THREAD

**Issue by fredrik-hammar** [shuttle-hq/shuttle#647]
I couldn't find any documentation on Shuttle.toml when looking for it and had to peek into the source code to see what you can configure there. It would be good to have documentation for it.

**Comment by ivancernja** [comment]
@fredrik-hammar Thanks for the feedback!

Yeah, currently our only mention of `Shuttle.toml` is in our docs where, inside the FAQ, it tells you that you can set a custom name for your project there (which is currently the only thing it is used for). I'll add an issue to our docs backlog re: putting the Shuttle.toml explanation more "up-front".

**Comment by Shubham8287** [comment]
I am looking to start contributing here, Would love to get this issue. 
The task looks straightforward on first sight, @ivancernja can you point out where in the docs you would like to add this info?

**Comment by ivancernja** [comment]
Hey @Shubham8287, happy to hear that! 😄 

I've copied the issue over to [shuttle-docs](https://github.com/shuttle-hq/shuttle-docs/) so feel free to take it from there. Thanks so much!

(closing this one)
