### ISSUE TITLE
List the running projects on the dashboard

### ISSUE THREAD

**Issue by piloer** [shuttle-hq/shuttle#683]
Because I'm used to sending completed code to Github and deleting the local code, I need to pull my project down and then enter the project directory to execute cargo shuttle logs --name xxxx when I need to view project logs.

**Comment by oddgrd** [comment]
Hey! We are planning this functionality, and we are about to start implementing it. It's going to take a little while, but you should see the first iteration in the coming weeks. 🙂

**Comment by jonaro00** [comment]
This should be covered by other fixes and the Shuttle Console.
`cargo shuttle logs --name xxxx` should always work regardless of directory and files.
