### ISSUE TITLE
[Bug]: "Callback handler failed" using cargo shuttle login

### ISSUE THREAD

**Issue by d2weber** [shuttle-hq/shuttle#697]
### What happened?

After using `cargo shuttle login` for the first time, I clicked the button on https://www.shuttle.rs/login and granted permission via Github, then I was redirected to https://www.shuttle.rs/api/auth/callback?code=longcode and got the Message:
`Callback handler failed. CAUSE: undefined`
Reloading the page gives:
`Callback handler failed. CAUSE: Missing state cookie from login request (check login URL, callback URL and cookie config).`
Going back to https://www.shuttle.rs/login and clicking the button again worked and I can see the dashboard.

### Version

v0.11.2

### Which operating systems are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
Browser logs:
Some cookies are misusing the recommended “SameSite“ attribute 10
Cookie “state” has been rejected because it is already expired. callback
Cookie “_state” has been rejected because it is already expired. callback
Cookie “max_age” has been rejected because it is already expired. callback
Cookie “_max_age” has been rejected because it is already expired. callback
Cookie “code_verifier” has been rejected because it is already expired. callback
Cookie “_code_verifier” has been rejected because it is already expired. callback
Cookie “nonce” has been rejected because it is already expired. callback
Cookie “_nonce” has been rejected because it is already expired. callback
Cookie “response_type” has been rejected because it is already expired. callback
Cookie “_response_type” has been rejected because it is already expired. callback
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
Thanks for the report! I have seen this before and it seems to be some issue with cookies, but I'm not sure why it happens yet... We're doing some work on the web side of things in the coming weeks, it may become clearer then. :crossed_fingers:

**Comment by jonaro00** [comment]
Things have improved a bit on this front. Login is now done in the Shuttle Console.
@GugaGongadze is this still relevant or can it be closed?

**Comment by GugaGongadze** [comment]
@jonaro00 This the same exact issue described here:
https://github.com/shuttle-hq/www/issues/71

Seems like latest report was 2 weeks ago.
We can close this issue in favor of the `www` one as this bug has nothing to do with this repo.
