### ISSUE TITLE
[Bug]: `watch shuttle run` together with rust-analyzer rebuilds crate from scratch every time

### ISSUE THREAD

**Issue by d2weber** [shuttle-hq/shuttle#699]
### What happened?

Consecutive calls to `cargo shuttle run` don't seem to cache the build artefacts, as it builds always all the dependencies from scratch. (And that can take a long time)
I used the tide template.

When using only `cargo build`, everything works fine. But after `cargo shuttle run` has been executed, also `cargo build` starts a clean build.

### Version

v0.11.2

### Which operating systems are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
Hey @d2weber! I just created a tide project with `cargo shuttle init`, and for me it does not rebuild from scratch, it starts immediately if it has already been built, and it recompiles very quickly if I make any changes. So I'm not sure why you are experiencing this :thinking: I'll ask around and see if anyone else has seen this.

**Comment by d2weber** [comment]
I believe I found the reason: I was using neovim and didn't realize that it starts rust-analyzer. I think the language server messed up the build directory. (Maybe also, because I was suspending neovim.)

**Comment by d2weber** [comment]
For reference, I got `cargo watch` to work with shuttle using the following tweaks similar to those in the [rust-analyzer manual](https://rust-analyzer.github.io/manual.html#compiler-feedback-from-external-commands):
* set `"rust-analyzer.checkOnSave": false` in preferences.
* Add the following task to `tasks.json`:
```json
  {
      "label": "Watch `shuttle run`",
      "group": "build",
      "type": "shell",
      "command": "cargo watch -x \"shuttle run\" -i Cargo.lock",
      "problemMatcher": "$rustc-watch",
      "isBackground": true
  }
```
I don't know, why those tweaks seem to be necessary to stop rust-analyzer and `shuttle run` triggering each other to build the crate from scratch, every time I edit a file.

**Comment by pogopaule** [comment]
> For reference, I got `cargo watch` to work with shuttle using the following tweaks similar to those in the [rust-analyzer manual](https://rust-analyzer.github.io/manual.html#compiler-feedback-from-external-commands):
> 
>     * set `"rust-analyzer.checkOnSave": false` in preferences.
> 
>     * Add the following task to `tasks.json`:
> 
> 
> ```json
>   {
>       "label": "Watch `shuttle run`",
>       "group": "build",
>       "type": "shell",
>       "command": "cargo watch -x \"shuttle run\" -i Cargo.lock",
>       "problemMatcher": "$rustc-watch",
>       "isBackground": true
>   }
> ```
> 
> I don't know, why those tweaks seem to be necessary to stop rust-analyzer and `shuttle run` triggering each other to build the crate from scratch, every time I edit a file.

I have the same problem with neovim. Is it correct that this solution works for VSCode but not neovim?

**Comment by d2weber** [comment]
I haven't used this solution a lot and it still recompiled sometimes everything, but at least it stoppes recompilation at some point.

I guess that you could configure rust analyzer with checkOnSave=false also for neovim but I don't know if it'd be easy to configure some kind of problemmatcher for cargo watch..
