### ISSUE TITLE
Write a README for `cargo-shuttle`

### ISSUE THREAD

**Issue by mikeando** [shuttle-hq/shuttle#71]
In the `[Deploying](https://docs.rs/shuttle-service/latest/shuttle_service/#deploying)` section there is a link to `cargo shuttle`
which links to `https://docs.rs/crate/cargo-shuttle/latest`. 

That leads to a valid page, but its main content is `cargo-shuttle-0.2.2 is not a library.` which is not particularly welcoming.

**Comment by brokad** [comment]
I agree. We should link to GH with a `README.md` for the [cargo-shuttle](https://github.com/getsynth/shuttle/tree/main/cargo-shuttle) crate instead.

**Comment by nahuakang** [comment]
@brokad @christoshadjiaslanis Looking for something to do :) If this is still required, can you let me know what's expected on the `README` (like a short bullet-point outline) and I can draft something?

**Comment by chesedo** [comment]
@nahuakang for anyone installing the cli tool this might still be nice though. A short bullet-point outline with a short description for each sub-command will be great.

Since the cli is not stable yet, I fear a proper documentation will create extra maintenance in the near future.

**Comment by chesedo** [comment]
@nahuakang Yes, please :smile:
