### ISSUE TITLE
[Feature]: Show latest log when no deployment is active

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#743]
### Describe the feature

Currently, when a deployment is not active:

```
$ cargo shuttle logs
Error: could not automatically find a running deployment for 'jonaro00-test'. Try passing a deployment ID manually
```

Instead of having to copy+paste the latest deployment id, simply show the log of the latest deployment. If no deployments, then show the error.

Alternatively, add `cargo shuttle logs --latest`.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by oddgrd** [comment]
Good idea! I prefer the `--latest` flag, but either is a big improvement in ergonomics.
