### ISSUE TITLE
[Enhancement]: Get rid of `cargo` dependency

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#756]
Current uses of bundled cargo (three subtasks):
- ~~**cargo-shuttle**~~ - Done #765 
  - ~~When using `shuttle init`. This can be replaced with a Command call.~~
  - ~~ToSemver when checking versions of cargo-shuttle and runtime. This is not strictly needed, a == is probably sufficient. (or just semver crate)~~
- ~~**deployer**~~ -  Done #907
  - ~~CliError is used when pre deploy testing. (can be replaced)~~
  - ~~Various enums and config struct used to construct the test command. All options used are easily used from CLI args.~~
- **service part 1** - Pending #922
  - is\_next and ensure\_{bin,cdylib}: can be done through `cargo_metadata`.
  - clean_crate: should be easily done with a command.
- **service part 2** - In progress by iamawacko #922
  - get_config: gets cargo config, but is never modified before use, so it is not needed if bundled cargo is not used.
  - get_compile_options: uses standard CLI options. (minor TODO here is to not limit cpus to 4 on local release run)
  - check_no_panic: ~~could be done by parsing toml i guess... (main challenge here is that `cargo config` is nightly)~~ -- can probably be dropped instead https://github.com/shuttle-hq/shuttle/issues/756#issuecomment-1488168471
  - build_workspace: figure out another way to find the crates of the workspace, as well as getting the data we need for the BuiltService struct.

**Comment by oddgrd** [comment]
Thanks again for this writeup @jonaro00, this looks good to me! For anyone that wants to pick this one up, it would be preferable to split this up into separate PRs, one for each crate outlined in the issue.

As for your additional suggestion, I'll need to think more about that one.

**Comment by jonaro00** [comment]
Yeah, at this point it is mainly a thing that could be kept in mind when designing this rewrite.

**Comment by oddgrd** [comment]
Before anyone takes this one further, we are currently working on supporting workspaces, so it may be good to hold off on this until we can verify that we can do that without the cargo library.

**Comment by chesedo** [comment]
The workspace support changes are in #767

**Comment by chesedo** [comment]
With the new runtime, I think we can also drop `check_no_panic` when making this change

**Comment by gautamprikshit1** [comment]
How do I test the deployer?

**Comment by oddgrd** [comment]
First run `USE_PANAMAX=disable make images`, then follow these steps: https://github.com/shuttle-hq/shuttle/blob/main/CONTRIBUTING.md#testing-deployer-only

You can also follow the contributing guide to set up the full shuttle environment locally, but following this guide to setup just deployer without gateway allows much faster iteration.

**Comment by iamwacko** [comment]
I am mostly finished, but I am a bit stuck on the `not_shuttle` test. Currently an ErrorDuringDrain happens, but I don't see anyway to reproduce that. Does anybody have any advice about how to make a panic occur when the runtime is missing? Or should the test be changed?
