### ISSUE TITLE
[Improvement]: Have concise error message for cargo shuttle stop

### ISSUE THREAD

**Issue by akhildevelops** [shuttle-hq/shuttle#766]
### Describe the feature

If there's no service running and I run `cargo shuttle stop` the error message is not comprehensible.

Below is the error message:

``` rust
vscode ➜ /workspaces/milna (feature/shuttle) $ cargo shuttle stop
Error: 404 Not Found
message: record could not be found
```
I think this message is directly coming from Database or some error in internal query.

``` rust
vscode ➜ /workspaces/milna (feature/shuttle) $ cargo shuttle stop
...
message: service is not running, cannot stop.
```

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by oddgrd** [comment]
Indeed, we should make this error clearer. So this will occur on any commands interacting with the currently running deployment if there isn't one. It might be enough to alter the `#[error(...)]` annotation in `deployer/handlers/error`, it will at least be a good short-term improvement.
