### ISSUE TITLE
[Bug]: stripping repository path fails on Windows

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#775]
### What happened?

Original from this thread: https://discord.com/channels/803236282088161321/1087505717776359586

```
Error: stripping repository path from working directory

Caused by:
    prefix not found
```

The `Path::strip_prefix` in `cargo-shuttle/src/lib.rs -> Shuttle::is_dirty` method seems to fail on Windows.
There are also other calls to that method which might need to be double checked.

### Version

v0.13.0

### Which operating systems are you seeing the problem on?

Windows

### Which CPU architectures are you seeing the problem on?

x86_64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by b1scoito** [comment]
Getting the same error, coincidentally, has just been fixed!

Waiting for the next release so I can test shuttle :D
