### ISSUE TITLE
[Bug]: Installation is failing on Ubuntu 20.04.6

### ISSUE THREAD

**Issue by matt628** [shuttle-hq/shuttle#778]
### What happened?

After executing the `cargo install cargo-shuttle` the  following error occurs  
` failed to run custom build command for 'shuttle-proto v0.13.0'`
Luckily, I managed to install shuttle by `cargo-binstall cargo-shuttle`

### Version

v0.13.0

### Which operating systems are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
error: failed to run custom build command for `shuttle-proto v0.13.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installY3zlYZ/release/build/shuttle-proto-93d68e635b2f199f/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=./provisioner.proto
  cargo:rerun-if-changed=./runtime.proto
  cargo:rerun-if-changed=./

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: runtime.proto:89:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nruntime.proto:90:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\n" }
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-shuttle v0.13.0`, intermediate artifacts can be found at `/tmp/cargo-installY3zlYZ`
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by ObamaTheLlama114** [comment]
I was having this issue on WSL Debian. I found that the latest version of protobuf in the Debian repositories was not recent enough for this to work. I uninstalled it with apt and reinstalled through Homebrew, which has a more recent version and that works.

**Comment by matt628** [comment]
Thanks, installing a newer version of protobuf helped.

**Comment by oddgrd** [comment]
> I was having this issue on WSL Debian. I found that the latest version of protobuf in the Debian repositories was not recent enough for this to work. I uninstalled it with apt and reinstalled through Homebrew, which has a more recent version and that works.

Yeah, unfortunately they are quite old. We have a note on this in our [protoc install guide](https://docs.shuttle.rs/support/installing-protoc#linux-and-mac), but this is quite a footgun. The good news is we are removing the protoc requirement in this weeks release (or the next release, at the latest). :partying_face:

**Comment by jonaro00** [comment]
Moved to #916
