### ISSUE TITLE
[Bug]: Cargo shuttle `Error: failed to make get request`

### ISSUE THREAD

**Issue by oxabz** [shuttle-hq/shuttle#779]
### What happened?

When I try to use any command of cargo shuttle that tries to access shuttle, I get an error.

I took a look at wireshark and it doesn't even get to the point of sending an HTTP request. So the error might be in cargo shuttle.

### Version

v0.13.0

### Which operating systems are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
Error: failed to make get request

Caused by:
    0: Request error: builder error: failed to parse header value
    1: builder error: failed to parse header value
    2: failed to parse header value
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oxabz** [comment]
Okay my bad (sort of). I seem to have used `ctrl+p` instead of `ctrl+shift+p` to paste my API key while logging in. 
After login in again correctly, the error is gone. 

I'm still leaving the bug open because it might be useful to add a check on the input of `cargo shuttle login`  or a more expressive error message in a future version.

**Comment by oddgrd** [comment]
Yeah, we should look into improving this error message. Thanks @oxabz!
