### ISSUE TITLE
[Feature]: pre-installed environment on `deploy` build machines

### ISSUE THREAD

**Issue by virtualritz** [shuttle-hq/shuttle#807]
### Describe the feature

This is related to #703.

It is not uncommon that a project may depend on crates that wrap code in other languages.
To have a hassle free experience at least the build tools for the most common cases should be installed on the machine that handles the `shuttle deploy` build step. 

I would assume this to be at least what a GH runner comes pre-installed with.

See [here](https://github.com/actions/runner-images#software-and-image-support) for what this entails on the resp. target platform/OS.

I would suggest starting with a C/C++ compiler and I would have some projects to test this.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by oddgrd** [comment]
So we are planning some changes to the deployer in the next couple of months that will affect how we do this. We are planning to no longer build services in the same container as they are started, but rather have a separate builder service (which we plan to use nix for, @chesedo is working on this and maybe able to elaborate). To include the dependencies you suggest should be simple when that is complete.

We can still get started on this in the meantime, by simply adding the dependencies we want in the [`deployer/prepare.sh`](https://github.com/shuttle-hq/shuttle/blob/main/deployer/prepare.sh) script. I think the dependencies you require and suggested are a good first start (C/C++ compiler). If you'd like to implement this a PR would be welcome.
