### ISSUE TITLE
[Improvement]: Use manual arg parsing in runtime instead of clap

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#819]
### Describe the feature

The args used are only used internally, so having the user-friendly clap parser adds unnecessary overhead.

Bonus: Also add a message when running without any args to suggest running `cargo shuttle run` instead. (this happens if user runs `cargo run`)

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by oddgrd** [comment]
Thanks @jonaro00, good idea! In a PR for this we should also make sure that the places where the runtime CLI is called is updated to work with these changes, e.g. `cargo shuttle run`.

/bounty 50
