### ISSUE TITLE
[Bug]: wildcard certificate for *.shuttleapp.rs does not cover base domain shuttleapp.rs

### ISSUE THREAD

**Issue by paulotten** [shuttle-hq/shuttle#833]
### What happened?

https://shuttleapp.rs/ on Chrome currently yields a certificate error. The certificate appears to be for "*.shuttleapp.rs" which does not include "shuttleapp.rs".

The certificate appears to be from "Let's Encrypt". Its been a while but I think I remember being able to include the base domain when creating a wildcard certificate with "Let's Encrypt".

### Version

n/a

### Which operating systems are you seeing the problem on?

Windows

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by paulotten** [comment]
> Chrome 

Firefox appears to get the same error (check the network monitor) then on its own initiative redirect to https://www.shuttleapp.rs/.

**Comment by paulotten** [comment]
Hey @iulianbarbu I think I've got the code written for this. https://github.com/shuttle-hq/shuttle/pull/968

I'm having issues testing it though. I'm trying to follow the steps from https://github.com/shuttle-hq/shuttle/blob/main/admin/README.md#how-to-test-custom-domain-certificates-locally

(will edit with logs)

**Comment by iulianbarbu** [comment]
Have you created an admin user and logged in before, per the CONTRIBUTING.md guide?
```bash
docker compose --file docker-compose.rendered.yml --project-name shuttle-dev exec auth /usr/local/bin/service --state=/var/lib/shuttle-auth init --name admin --key dh9z58jttoes3qvt
```
```bash
cargo run --bin cargo-shuttle -- login --api-key "dh9z58jttoes3qvt"
```

```

**Comment by paulotten** [comment]
@iulianbarbu yes.

Longer answer: I hadn't done it since last remaking the images. Running the docker command now however I get a "UNIQUE constraint failed" error, so the container still has the admin user saved. Checking `~/.config/shuttle/config.toml` I see the api key listed above. So I think I'm already good on this step.
