### ISSUE TITLE
[Feature]: rename "examples" repository to "shuttle-examples"

### ISSUE THREAD

**Issue by paulotten** [shuttle-hq/shuttle#837]
### Describe the feature

https://github.com/shuttle-hq/examples

"Examples" is a very generic name. In the context of "shuttle-hq/examples" it's clear enough.

It is used as a submodule of "shuttle-hq/shuttle" however. When a contributor forks "shuttle-hq/shuttle" to (by default) "contributor/shuttle" the `.gitmodules` file expects "shuttle-hq/examples" to be similarly forked to "contributor/examples". This is less clear and runs the risk of the repository name already being taken since it is a common word.

The contributor could rename their fork of "examples" to something else. Then however they would need to update `.gitmodules`, and then make sure they never commit that change.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by oddgrd** [comment]
This has been implemented now: https://github.com/shuttle-hq/shuttle-examples , we just need to update some links and then we'll close this. Thanks for the suggestion Paul!
