### ISSUE TITLE
[Bug]: missing logs for Tide projects (and possibly Axum?)

### ISSUE THREAD

**Issue by AlphaKeks** [shuttle-hq/shuttle#839]
### What happened?

When running a cargo shuttle run for a tide project, the log outputs are less than running a tide project without shuttle.

I have also seen this happen with Axum projects, specifically `ERROR` level logs.

### Version

v0.15.0

### Which operating systems are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by utterstep** [comment]
@oddgrd can you please reassign it to me?
https://discord.com/channels/803236282088161321/1101504029584007248/1103012250211594269

Started researching here: https://github.com/vroussea/tide-logs/pull/1/

**Comment by vroussea** [comment]
Here is the PR to fix the missing logs : https://github.com/shuttle-hq/shuttle/pull/864

**Comment by utterstep** [comment]
Fixed in #864 :)
