### ISSUE TITLE
[Feature]: Add a health endpoint to all services

### ISSUE THREAD

**Issue by Cyril-Cf** [shuttle-hq/shuttle#840]
### Details

We want to eventually send a notification to users when their service goes down. But for this we need to know a service is still healthy.

### Requirements

- Create a `/healthz` endpoint on every service under `/services`
    - Have return just a status code of 200

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by frectonz** [comment]
I will also be working this

**Comment by jonaro00** [comment]
The team is evaluating a new approach to this problem.

**Comment by jonaro00** [comment]
Closing this in favour of #1557
