### ISSUE TITLE
[Feature]: Remove /hello from all the examples

### ISSUE THREAD

**Issue by mikegin** [shuttle-hq/shuttle#841]
### Describe the feature

Almost all of the examples (hello world) register a /hello endpoint. This confuses a lot of new users who try to access them on the root endpoint (/).

### Requirements

- Go through all the hello world examples and update their endpoint if needed.
- Go through all the other examples and update their main endpoints if needed.
- Update any example docs if that would help too (hello world examples and none hello world examples)
- Update tests that call the `/hello` endpoint

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by paulotten** [comment]
This is interfering with testing https://github.com/shuttle-hq/shuttle/issues/849

**Comment by paulotten** [comment]
https://github.com/shuttle-hq/shuttle-examples/pull/41 and https://github.com/shuttle-hq/shuttle/pull/863 merged.

I believe this can be closed now.

**Comment by oddgrd** [comment]
Indeed, thanks!
