### ISSUE TITLE
[Feature]: Improve errors for panics in the main function

### ISSUE THREAD

**Issue by piewhat** [shuttle-hq/shuttle#843]
### Describe the feature

Currently a few panics in the main function will return a log error of no panic message, which is the default if no panic message is received in the alpha runtime: https://github.com/shuttle-hq/shuttle/blob/main/runtime/src/alpha/mod.rs#L330

Requirements
- Reproduce this on a local environment
- Investigate why it is happening
- Propose a solution to fix it

### Duplicate declaration

- [x] I have searched the issues and this feature has not been requested before.

**Comment by piewhat** [comment]
Team: Clawed Crusaders

**Comment by pedromfedricci** [comment]
If anyone has any leads on reproducing this it would be great! :)

**Comment by oddgrd** [comment]
We have had a few reports of this on discord, a search for `no panic message` should yield some results. Thanks for picking this up!
