### ISSUE TITLE
[Feature]: Refactor database resources to no longer cycle passwords (ENG-551)

### ISSUE THREAD

**Issue by ankitpatel96** [shuttle-hq/shuttle#844]
## Description

Historically we never stored the credentials for DBs and this meant we had to cycle the credentials for every new deploy.  But since we now stored the credentials, we no longer need to cycle them.  Cycling the RDS credentials also takes 1+ minutes.

## Requirements:

- refactor the functions for provisioning a database user in provisioner/lib.rs so that if a user already exists the password is no longer cycled
- Update deployer to always send down the details of persisted resources

### Suggestion or Example of how the feature would be used

@Shariffintech and I will be working on this

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by Shariffintech** [comment]
@oddgrd could you also add me as a participant on this ticket?

**Comment by oddgrd** [comment]
Hey @Shariffintech and @ankitpatel96, are you still interested in this issue? If not I'll just open it up again :slightly_smiling_face:

**Comment by oddgrd** [comment]
Hey! So this issue has been resolved, we will now get the resource information from the resource-recorder if it already exists, meaning the call to provisioner that lead to the cycling of passwords no longer occurs. However, we might need to create a new command that allows users to cycle their database password, in case their password is leaked. We're currently working on resource deletion, but we'll discuss this internally and open a new ticket as soon as we have the capacity to review it.

**Comment by Shariffintech** [comment]
🫡 Thank you for the update @oddgrd! I'm glad to hear that the problem has been addressed. Looking forward to contributing to the new command for resource deletion whenever it's the right time, happy to assist.
