### ISSUE TITLE
Object persistence from annotations

### ISSUE THREAD

**Issue by brokad** [shuttle-hq/shuttle#86]
Currently the only form of persistence across runs of a service is an (optional) database accessible via [Factory](https://docs.rs/shuttle-service/0.2.4/shuttle_service/trait.Factory.html). 

Maybe we could allow users to "persist" a serializable/deserializable object across runs with a simple derive annotation

```rust
#[derive(Serialize, Deserialize, Persist)]
struct MyPersistingState {
  view_counter: usize
}
```

**Comment by Butch78** [comment]
I'll give this a go!

**Comment by chesedo** [comment]
This was added with the new [persist resource](https://docs.shuttle.rs/resources/shuttle-persist) in v0.6.0
