### ISSUE TITLE
[Feature]: Support delete project

### ISSUE THREAD

**Issue by southorange0929** [shuttle-hq/shuttle#865]
### Describe the feature

Is it possible for me to delete already existed project in my account with command line?

### Suggestion or Example of how the feature would be used

For example:
```shell
cargo shuttle project delete(remove) --name=xxx
```

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by paulotten** [comment]
https://docs.shuttle.rs/introduction/shuttle-commands

I believe `stop` does this.

**Comment by southorange0929** [comment]
You are right! But it still can be listed with `cargo shuttle project list`.
Any methods to delete this record from project list?
<img width="1090" alt="图片" src="https://user-images.githubusercontent.com/32590310/236594135-3e63309e-ea12-4780-896a-a9cb009bf7ae.png">

**Comment by Banyc** [comment]
The `stop` command requires a `--working-directory` to be presented, which could be a hassle. For instance, I want to destroy/remove a project that no longer exists in source code.

The proposed `delete` should also avoid relying on the existing code base IMO.

**Comment by oddgrd** [comment]
Hey! No, it's not possible currently to completely delete a project completely, although we are working on it. It has been blocked by missing functionality for deleting resources (which would need to happen first), but a contributor has implemented that now, so complete deletion of a project should be possible to implement soon. I'll try to update this issue when we can get started on it.

**Comment by Banyc** [comment]
@jonaro00 After I ran two variants of `stop`:

![image](https://github.com/shuttle-hq/shuttle/assets/36535895/9811cd6a-7815-4220-83e8-8692f53858f6)

![image](https://github.com/shuttle-hq/shuttle/assets/36535895/9e08b69c-2f90-4d5c-805c-c72c0b520678)

In comparison, this is `list` command:

![image](https://github.com/shuttle-hq/shuttle/assets/36535895/4740b684-69cb-49e2-809d-6c2f4d1b8775)

**Comment by jonaro00** [comment]
@Banyc Aha, I see now. It requires you to be in *any* Cargo folder. It loads the Cargo metadata of the folder you're in before it overrides the crate name with `--name` 😅. This should be a quite simple fix. You can open a bug report on this if you want.

**Comment by jonaro00** [comment]
Project deletion is supported since 0.30.0
