### ISSUE TITLE
[Feature]: Handling regular signals sent to cargo-shuttle on Windows

### ISSUE THREAD

**Issue by pedromfedricci** [shuttle-hq/shuttle#872]
### Describe the feature

We must handle gracefully when the local deployment of user services is interrupted by sending a signal to the cargo-shuttle project, or any of the user’s services panic, or the cargo-shuttle process is gracefully killed. At this moment we cover some of these in cargo-shuttle for *unix systems (SIGINT, SIGTERM, and user service panic). We must do similar handling for regular signals sent to cargo-shuttle process on Windows.

Requirements:
* reproduce the issue first, so you can verify your solution works.
* add support for Windows common signals handling by killing the shuttle-runtimes gracefully upon the cargo-shuttle process receiving them, or user’s services panic at load time.
* use tokio::signal windows support: https://docs.rs/tokio/latest/tokio/signal/windows/index.html.
* Optional: think about what would be required to gracefully stop all the runtimes upon one of them receiving a signal or panics later during the runtime (for both windows and linux).

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by pedromfedricci** [comment]
ping buddy @piewhat

**Comment by Shubham8287** [comment]
I went through the SIG* handlers for UNIX, and able to reproduce the issue on windows. Stabbing into it.
/attempt #852
