### ISSUE TITLE
Customizable Host headers

### ISSUE THREAD

**Issue by brokad** [shuttle-hq/shuttle#88]
Currently the deployment router at the edge will use the value of the `Host:` header to decide where to route requests and by default will only accept `my-project-name.shuttleapp.rs`. This is not ideal for self-deployments which are not deployed as a subdomain of `shuttleapp.rs`.

We could expose a parameter in `Shuttle.toml` which lets users configure a `Host` key for their deployment.

**Comment by tomkarw** [comment]
Is this up for grabs? I could give it a go.

**Comment by jonaro00** [comment]
Closing in favour of #1563 #1584
