### ISSUE TITLE
[Feature]: push-based model for starting the project

### ISSUE THREAD

**Issue by utterstep** [shuttle-hq/shuttle#884]
### Describe the feature

Currently the `project start` command in the cargo-shuttle CLI will send requests to the gateway in a loop to get the status of the project until it is ready (or crashed/errored), showing a spinner until it concludes. This is a pull-based model. 

It would be more efficient to refactor this to a push-based model, meaning we setup a websocket connection in the gateway that we connect to when we call `project start`, and then we show the spinner until we receive a message on the websocket with a final state (ready, crashed, errored).

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by utterstep** [comment]
@vroussea started working on this one :)

**Comment by jonaro00** [comment]
Closing due to being solved on the shuttle.dev platform.
