### ISSUE TITLE
[Feature]: DynamoDB Resource

### ISSUE THREAD

**Issue by mikegin** [shuttle-hq/shuttle#895]
### Describe the feature

Extending available auto provisioned resources to include non SQL (AWS RDS) type. DynamoDB would be a good candidate as is popular and still based in AWS.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by paulotten** [comment]
We probably want to be able to run locally. See https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html

**Comment by paulotten** [comment]
@oddgrd I assume you are aware of https://github.com/shuttle-hq/shuttle/pull/910/files#diff-9aa440c73eedfd63ea9f7221d4be2d948eb7af1bffaadd9eec69a379ab1c9cadR659?

That policy restricts users access to only tables that match the assigned prefix.

**Comment by oddgrd** [comment]
Oh, sorry, that was a bit unclear. Our main concern was that we had to give permissions to the provisioner to create users and policies. So we want to find a way to support resources like dynamodb and s3 (where we can't just return a public URL like we do for RDS) without needing those permissions in the provisioner.

**Comment by jonaro00** [comment]
Closing in favour of #1568
