### ISSUE TITLE
[Feature]: Support custom features (`--features`) for `run` and `deploy` commands

### ISSUE THREAD

**Issue by orhun** [shuttle-hq/shuttle#913]
### Describe the feature

In my project, I'm using a separate cargo feature for enabling the shuttle builds:

```toml
[features]
default = []
shuttle = [
  "shuttle-actix-web",
  "shuttle-runtime",
  "shuttle-static-folder",
  "tokio",
]
```

However I can't use this feature for `cargo shuttle` thus any shuttle command that I run fails.

### Suggestion or Example of how the feature would be used

Add an argument for `cargo shuttle` subcommands for enabling custom features. For example:

```sh
$ cargo shuttle run --features shuttle
```

```
$ cargo shuttle deploy --features shuttle
```

I'm happy to work on a PR if it is applicable.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by orhun** [comment]
I added `--features` argument to `run` in #914 

I'm not sure how `deploy` subcommand works so I need some guidance there 🐻

**Comment by jonaro00** [comment]
Custom feature flags were added in https://github.com/shuttle-hq/shuttle/releases/tag/v0.46.0

**Comment by orhun** [comment]
hell yea
