### ISSUE TITLE
[Bug]: Commands need to be executed from a Cargo folder even when `--name` is used

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#927]
### What happened?

Context:
https://github.com/shuttle-hq/shuttle/issues/865#issuecomment-1545226936
https://github.com/shuttle-hq/shuttle/issues/865#issuecomment-1545389360

Commands that need to know what project is targeted check the current directory for a Cargo manifest or a Shuttle.toml before the `--name` parameter is even considered, even though it has higher priority.

### Version

v0.16.0

### Which operating systems are you seeing the problem on?

macOS, Windows, Linux

### Which CPU architectures are you seeing the problem on?

x86_64, ARM64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by imor** [comment]
@jonaro00 Could you please assign it to me, I'd like to take a stab at it.
