### ISSUE TITLE
[Feature]: Log paths of all files included in deployment archive

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#930]
### Describe the feature

Many questions are posted regarding which files are uploaded to Shuttle.
The answer is quite simple (This should be listed in the docs btw), but it is hard to verify exactly which files are uploaded. The code for handling this is in an obscure place and not very straight forward.
Therefore, either cargo-shuttle or the logs from deployment should log all files that were included in the archive, i.e. either when making the archive or unpacking it.

Perhaps this will spam the logs a bit, so perhaps a `--verbose` flag could be introduced for deployments?

Alternatively, it could be a development build logging feature.

### Suggestion or Example of how the feature would be used

Packing file .gitignore
Packing file Cargo.toml
...
Packing file src/main.rs
...

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by imor** [comment]
Another idea might be to write the archive to disk locally for debugging. Users can then inspect the archive to confirm which files are included in it.

**Comment by hseeberger** [comment]
I already considered running the deployer locally and add logging. So I like this idea. `trace` level makes sense for me for this use case.

I also like the alternative. Write the archive to disk and log (`info` level) the path.

**Comment by jonaro00** [comment]
I like the idea with a tracing log in cargo-shuttle. It show up for the end user if they ran deploy with RUST_LOG, right? In that case, perhaps an info level log would be good.

**Comment by imor** [comment]
Yes these logs can be enabled by setting the RUST_LOG env variable. E.g. to see only cargo_shuttle info logs, set RUST_LOG=cargo_shuttle=info. Added PR #931 for it.
