### ISSUE TITLE
[Feature]: Add more deployment metadata

### ISSUE THREAD

**Issue by hseeberger** [shuttle-hq/shuttle#941]
### Describe the feature

The deployments table doesn’t account for VCS information, which is regularly useful to map the deployments to git commits. We want to extend the deployments table scheme with information related to the local git repository of the user project. This is possible because when using cargo to create projects, they’ll get a git repository initiated as well, so we can assume that Shuttle projects will benefit from git from the beginning.

## Requirements

Extend the deployer model with information about the last commit message, commit id, branch name, and whether the branch is dirty or not.

## Shuttle Batch 2.0

See https://www.notion.so/Add-more-deployment-metadata-f83c3e07fb67491fae99ac7ccc527c3d.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by hseeberger** [comment]
Questions to be clarified:

- Should we ensure about backward compability?
  - If so, should we use optional fields in Rust and nullable columns in the database?
- Should this feature include populating the extended deployment model?
  - If not, should we use nullable columns or insert dummy values, e.g. for commit message and id
  - If yes, where do we get the data from? Should we use the query params of the deployer::create_service handler?

**Comment by iulianbarbu** [comment]
> * Should we ensure about backward compability?

Old deployments will lack this data and we should handle it gracefully.
   
>   * If so, should we use optional fields in Rust and nullable columns in the database?

Whatever makes it such that we can handle the old deployments gracefully. I think optional fields and nullable columns should do it.

> * Should this feature include populating the extended deployment model?

If by this you mean populating the existing deployments that haven't benefited from the new metadata, I don't think we'll need this if we can handle the old deployments gracefully, meaning we should be able to return only the existing metadata, even if the deployments model has more than that. The clients should be able to handle this and display the deployment information either way.

Hope this answers your qs but if not please let me know.

**Comment by hseeberger** [comment]
Thanks, @iulianbarbu.

Populating the model (last question) was pretty unclear wording, I guess ;-)

Let me put it this way: After extending the `Deployment` with additional fields, e.g. `git_commit_id`, we need to fill these fields, e.g. before invoking `create_service` (which is calling `persistence::insert_deployment`). The project/issue description only mentions "Extend the deployer model", it does not mention where to get the values to fill these new fields.

So my question was whether we should (a) use dummy values or just `None`/`NULL` or (b) also extend the endpoint (semantically) by using additional query params of the deployer::create_service handler.

I guess (b) is the case. Please clarify.

**Comment by iulianbarbu** [comment]
Ah, I see now. I missed talking about the endpoint. Yes, b) would be the preferred approach. Thanks a lot for clarifying. 😊

**Comment by iulianbarbu** [comment]
> Ah, I see now. I missed talking about the endpoint. Yes, b) would be the preferred approach. Thanks a lot for clarifying. 😊

Or, in case we can derive the git information from the archive we sent over, then the endpoint might be excluded. However, I think we're not packaging git information when sending over the source code from the user to the deployer (for building the code), so the endpoint approach might be the only way.
