### ISSUE TITLE
[Bug]: response from deployer is invalid.

### ISSUE THREAD

**Issue by nikthechampiongr** [shuttle-hq/shuttle#953]
### What happened?

Attempting to use commands such as cargo shuttle deployment list, or cargo shuttle status leads to 502 Bad Gateway Error. And asks you to submit a ticket.

I did find a similar issue, specifically #328 but it appears to be from 2022.

### Version

v0.17.0

### Which operating systems are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
Error: 502 Bad Gateway
message: response from deployer is invalid. Please create a ticket to report this
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by Alliance-Administrator** [comment]
Same here

**Comment by jonaro00** [comment]
From Discord:
> chesedo: Our gateway is currently having issues. We are working on fixing it and will have an update soon

**Comment by nikthechampiongr** [comment]
From discord:

> chesedo: Our infra is fixed. There should be no more "502 Bad Gateway" errors
