### ISSUE TITLE
[Bug]: Serenity bot crashes due to excessive logs

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#955]
### What happened?

Serenity projects emit way too many log lines since #864, and can lead a bot to crash (not 100% confirmed).

The excessive logs are due to functions annotated with `#[instrument]` (spans) are set to INFO by default.

I think we can compromise by having the minimum level increased in the Shuttle log consumer for spans,
but it would be awesome if this was separately configurable with #842 (set separate span and event levels, per crate)

### Version

v0.17.0

### Which operating system(s) are you seeing the problem on?

Linux, In deployment

### Which CPU architectures are you seeing the problem on?

x86_64, In deployment

### Relevant log output

```sh
2023-05-31T02:03:10.586481275Z  INFO {shard="Shard { shard_info: ShardInfo { id: 0, total: 1 }, .. }"} serenity::gateway::bridge::shard_runner: [span] recv
2023-05-31T02:03:10.586582375Z  INFO serenity::gateway::shard: [span] do_heartbeat
2023-05-31T02:03:10.586616675Z  INFO {shard="Shard { shard_info: ShardInfo { id: 0, total: 1 }, .. }"} serenity::gateway::bridge::shard_runner: [span] recv_event
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by techs-sus** [comment]
I agree with this. Even though my bot isn't crashing, I am concerned about the ever expanding log file. These "span" log messages take up hundreds of lines of space in the file.

Besides, it makes hosting shuttle more expensive 😔.

**Comment by oddgrd** [comment]
Thanks for getting to the bottom of this @jonaro00! If the #842 param takes a `RUST_LOG` string, would that resolve this? If we can't get that over the line for the next release we could also  change the minimum level in the spans consumer as you suggested, since IIRC only tide users were affected by missing logs before #864. And we have very few tide users (I reported the initial bug).

**Comment by jonaro00** [comment]
From what I understand, the RUST_LOG only targets events by defaults, and not spans. Not sure how complex the difference is.

I'll try lowering the span log level.
