### ISSUE TITLE
[Bug]: status column values are misaligned in project list table output

### ISSUE THREAD

**Issue by oddgrd** [shuttle-hq/shuttle#962]
### What happened?

When running `project list` the values of the `Status` column are misaligned, this seems to be related to how we apply the color.  If we remove the `.<color>` call from the `project::State` display impl the table will be correctly aligned, but we need the color in the display impl for other calls (like `project::Response`).

Screenshot of current output:
![image](https://github.com/shuttle-hq/shuttle/assets/29732646/54b4e41a-6c09-4733-8e98-2b26c4d1f1f6)

### Version

v0.17.0

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
Why does this not happen on deployment list? 
![image](https://github.com/shuttle-hq/shuttle/assets/54029719/e3898e20-fc9a-4dd6-89de-9704847fa686)

**Comment by SyedFasiuddin** [comment]
This difference might be causing this issue. I'm not sure.

https://github.com/shuttle-hq/shuttle/blob/316b7a3b2a9ff3b5a60507871c35f138e565c357/common/src/models/deployment.rs#L50

https://github.com/shuttle-hq/shuttle/blob/316b7a3b2a9ff3b5a60507871c35f138e565c357/common/src/models/project.rs#L158

I'll look into this.

**Comment by lecoqjacob** [comment]
I did some digging into this and found the culprit. My first debugging attempt was to replace `project.state` with the string equivelent. I.E. `Ready => "ready"`.

This printed the table with the correct format. Since the deployment list was experiencing no issues, I started comparing the setup of `project list` to `deployment list`. Turns out, that deployment state uses `Strum::Display` and project state use `Strum::EnumString`.

Switching out `EnumString` for `Display` showed the table in the correct formatting. 

This issue now is we have a custom Display impl on `Project Status`. How do we want to proceed?

**Comment by lecoqjacob** [comment]
![image](https://github.com/shuttle-hq/shuttle/assets/9278174/fbb4a129-67b4-4245-bf15-8af7b377838d)

**Comment by oddgrd** [comment]
Oh, sorry I missed this @lecoqjacob, thanks for figuring it out! Would you mind opening a PR for this so we can see the changes required? If you could include the screenshot of the output/take a new one, that would be great too.

**Comment by jonaro00** [comment]
Deployment State uses `.fg(state.get_color())` and colors the entire cell, while project State has more customization about which words are colored.

Shall we simplify the latter to only have one color for the entire string (for each state) associated with it? (make project State like deployment State)

**Comment by jonaro00** [comment]
We have now decided that the above comment is a good solution to this problem.
Anyone who wants, feel free to pick it up.
Let us know if more clarity is needed.

**Comment by supleed2** [comment]
I'd like to try this issue.

So the goal is to replace the manual `impl Display` with the derive macro of `Strum::Display` yet somehow show the custom fields?

Looking at the macro, it uses `std::fmt::Formatter::pad` for the `to_string` attribute which doesn't allow formatting the fields, but maybe the `serialize` attribute might work?

Also, is the api.unstable.shuttle.rs endpoint still usable as a test, it would be good to get a json response with a range of different values?
