### ISSUE TITLE
[Bug]: `cargo +nightly sort --workspace` fails

### ISSUE THREAD

**Issue by paulotten** [shuttle-hq/shuttle#963]
### What happened?

While running `cargo +nightly sort --workspace` as per CONTRIBUTING.md, we got the following error. It is not related to our changes, we haven't touched that file.

```
$ cargo +nightly sort --workspace
Checking shuttle...
Finished: Cargo.toml for "shuttle" has been rewritten
Checking admin...
Finished: Cargo.toml for "admin" has been rewritten
Checking auth...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TomlError { message: "TOML parse error at line 3, column 8\n  |\n3 | version.workspace = true\n  |        ^\nUnexpected `.`\nExpected `=`\n" }', /home/mike/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-sort-1.0.9/src/sort.rs:113:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`cargo-sort` appears not to like/understand the period in `version.workspace = true` of line 3 of `auth/Cargo.toml`. I'm guessing this command hasn't been run in a while.

### Version

head

### Which operating system(s) are you seeing the problem on?

Linux

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
Woops, this should have been removed from the contributing doc, as cargo-sort doesn't support workspace inheritance yet. :smile:
