### ISSUE TITLE
[Bug]: Is viable to rewrite my project?

### ISSUE THREAD

**Issue by asensio-project** [shuttle-hq/shuttle#969]
### What happened?

I have an [actix-web project](https://github.com/asensio-project/trivial_packager). I want to publish this page to the internet. The vast majority of hosting services were for PHP, Java, Python... except this hosting service.

But my question is, is viable for me to rewrite my project using shouttle? Is there any easy way?

(I know that this isn't bug, but I have trouble with Discord)

### Version

v0.17.0

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
It looks doable. You would need to rewrite the main function and database logic to use the equivalent Shuttle resources.

**Comment by asensio-project** [comment]
And what about all the structures of diesel, how can I continue using them?
