### ISSUE TITLE
[Feature]: Preview Deployments

### ISSUE THREAD

**Issue by iamwacko** [shuttle-hq/shuttle#971]
### Describe the feature

Shuttle describes itself as a `Vercel for backends`, and [preview deployments](https://vercel.com/docs/concepts/deployments/preview-deployments) are a very useful feature of Vercel. Basically it allows you to create deployments that aren't directly to the production site, but to preview URL. This URL can then be shared with team members or used for testing. Only the latest preview build should be kept.

### Suggestion or Example of how the feature would be used

On the user side this would be something like an extra flag for `cargo shuttle deploy` and some modifications to the GH actions deployer. On our side that would mean we would have a subdomain (or maybe a seperate domain) just for previews. We could then have each of the previews differentiated by the git hash. 

We would also have to make changes to `auth` and `gateway` to let this happen.

### Duplicate declaration

- [X] I have searched the issues and this feature has not been requested before.

**Comment by jonaro00** [comment]
Similar to #177

**Comment by iamwacko** [comment]
Your right, its wording was just different enough that it didn't come up in any of my searches.
