### ISSUE TITLE
[Improvement]: Show deployment metadata in deployment table

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#981]
## Part 2 of #941 

#943 added more metadata to deployments.
The task is to add this info to the `cargo shuttle deployment list` table.
Beware that screen width is limited, so perhaps only the first 7 chars of the commit id and first ~20(?) chars of the commit message are needed, play around and see what is suitable.

- Start by expanding the response model of `get_deployments()` in deployer/src/handlers/mod.rs
- Then, extend the table in `get_deployments_table()` in cargo-shuttle/src/lib.rs

### Duplicate declaration

- [X] I have searched the issues and this improvement has not been requested before.

**Comment by Fuzzicles** [comment]
This looks interesting! I wanted to get my local development server setup before commenting, and I just got it working. I'm unfamiliar working in a codebase this large, but I'll give it a shot and see what I can do.
