### ISSUE TITLE
[Bug]: Version check of existing shuttle-next binary panics

### ISSUE THREAD

**Issue by jonaro00** [shuttle-hq/shuttle#992]
### What happened?

Running a next project installs shuttle-next if not present.
If it exists, the --version flag is used to check it.
Since https://github.com/shuttle-hq/shuttle/pull/822/files#diff-651941ab3b205fa0a1385341412700b34be3a850f36cf002fe60810f4ba89e2aL4 , the version flag is no longer there.
Therefore, running `cargo shuttle run` with shuttle-next installed panics, so it only works the first time.

I think the automatic install (in prod build) is strange.
I'd prefer getting prompted to `cargo install` so that I actually know what's happening. The user already installed cargo-shuttle and does not need to be spoonfed IMO.

The version check is still required though, so it could be solved by checking for "--version" explicitly before `NextArgs::parse()`.

### Version

v0.18.0

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
Installing shuttle-next runtime. This can take a while...
thread 'main' panicked at 'shuttle-runtime version should be in the `name version` format', /home/jonaro00/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-shuttle-0.18.0/src/lib.rs:1283:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by jonaro00** [comment]
@paulotten What do you think about my point regarding automatic install vs prompting for manual install? ^

**Comment by geoffreygarrett** [comment]
?????????
